

#ifndef PROT_DECL

#define PROT_DECL(name)		extern void name(Vec_Obj_Args *oap );

PROT_DECL( vsqrt )
PROT_DECL( vsin )
PROT_DECL( vcos )
PROT_DECL( verf )
PROT_DECL( vatan )
PROT_DECL( vtan )
PROT_DECL( vabs )
PROT_DECL( vsign )
PROT_DECL( vlog10 )
PROT_DECL( vlog )
PROT_DECL( vexp )
PROT_DECL( vneg )
PROT_DECL( rvneg )
PROT_DECL( cvneg )
PROT_DECL( qvneg )
PROT_DECL( vsqr )
PROT_DECL( vfloor )
PROT_DECL( vceil )
PROT_DECL( vround )
PROT_DECL( vrint )
PROT_DECL( vj0 )
PROT_DECL( vj1 )
PROT_DECL( vacos )
PROT_DECL( vasin )
PROT_DECL( vatn2 )
PROT_DECL( vmov )
PROT_DECL( vnot )
PROT_DECL( vcomp )
PROT_DECL( vconj )
PROT_DECL( vmgsq )
PROT_DECL( vuni )
PROT_DECL( vfft )
PROT_DECL( vift )

PROT_DECL( vsp2by )
PROT_DECL( vsp2in )
PROT_DECL( vsp2di )
PROT_DECL( vsp2dp )

PROT_DECL( vby2in )
PROT_DECL( vby2di )
PROT_DECL( vby2sp )
PROT_DECL( vby2dp )

PROT_DECL( vin2by )
PROT_DECL( vin2di )
PROT_DECL( vin2sp )
PROT_DECL( vin2dp )

PROT_DECL( vdp2by )
PROT_DECL( vdp2in )
PROT_DECL( vdp2di )
PROT_DECL( vdp2sp )

PROT_DECL( vdi2by )
PROT_DECL( vdi2in )
PROT_DECL( vdi2sp )
PROT_DECL( vdi2dp )

PROT_DECL( vuby2by )
PROT_DECL( vuby2in )
PROT_DECL( vuby2di )
PROT_DECL( vuby2sp )
PROT_DECL( vuby2dp )
PROT_DECL( vuby2uin )
PROT_DECL( vuby2udi )

PROT_DECL( vuin2by )
PROT_DECL( vuin2in )
PROT_DECL( vuin2di )

PROT_DECL( vuin2sp )
PROT_DECL( vuin2dp )
PROT_DECL( vuin2uby )
PROT_DECL( vuin2udi )
PROT_DECL( vudi2by )
PROT_DECL( vudi2in )
PROT_DECL( vudi2di )
PROT_DECL( vudi2sp )
PROT_DECL( vudi2dp )
PROT_DECL( vudi2uby )
PROT_DECL( vudi2uin )
PROT_DECL( vby2uby )
PROT_DECL( vin2uby )
PROT_DECL( vdi2uby )
PROT_DECL( vsp2uby )
PROT_DECL( vdp2uby )
PROT_DECL( vby2uin )
PROT_DECL( vin2uin )
PROT_DECL( vdi2uin )
PROT_DECL( vsp2uin )
PROT_DECL( vdp2uin )
PROT_DECL( vby2udi )
PROT_DECL( vin2udi )
PROT_DECL( vdi2udi )
PROT_DECL( vsp2udi )
PROT_DECL( vdp2udi )
PROT_DECL( vset )
PROT_DECL( vatan2 )
PROT_DECL( vmin )
PROT_DECL( vmax )
PROT_DECL( vadd )
PROT_DECL( vsub )
PROT_DECL( vmul )
PROT_DECL( vdiv )
PROT_DECL( vpow )
PROT_DECL( vand )
PROT_DECL( vnand )
PROT_DECL( vor )
PROT_DECL( vxor )
PROT_DECL( vminm )
PROT_DECL( vmaxm )
PROT_DECL( vmod )
PROT_DECL( vcmul )
PROT_DECL( vbnd )
PROT_DECL( vibnd )
PROT_DECL( vshr )
PROT_DECL( vshl )
PROT_DECL( vsatan2 )
PROT_DECL( vsatan22 )
PROT_DECL( vsmin )
PROT_DECL( vsmax )
PROT_DECL( vsmnm )
PROT_DECL( vsmxm )
PROT_DECL( vsadd )
PROT_DECL( vssub )
PROT_DECL( vsmul )
PROT_DECL( vsdiv )
PROT_DECL( vsdiv2 )
PROT_DECL( vcsmul )
PROT_DECL( vqsmul )
PROT_DECL( vspow )
PROT_DECL( vspow2 )
PROT_DECL( vclip )
PROT_DECL( viclp )
PROT_DECL( vsmod )
PROT_DECL( vsmod2 )
PROT_DECL( vscml )
PROT_DECL( vsand )
PROT_DECL( vsor )
PROT_DECL( vsxor )
PROT_DECL( vsshr )
PROT_DECL( vsshr2 )
PROT_DECL( vsshl )
PROT_DECL( vsshl2 )
PROT_DECL( vramp1d )
PROT_DECL( vramp2d )
PROT_DECL( vvv_slct )
PROT_DECL( vvs_slct )
PROT_DECL( vss_slct )

PROT_DECL( vv_vv_lt )
PROT_DECL( vv_vv_gt )
PROT_DECL( vv_vv_le )
PROT_DECL( vv_vv_ge )
PROT_DECL( vv_vv_eq )
PROT_DECL( vv_vv_ne )

PROT_DECL( vv_vs_lt )
PROT_DECL( vv_vs_gt )
PROT_DECL( vv_vs_le )
PROT_DECL( vv_vs_ge )
PROT_DECL( vv_vs_eq )
PROT_DECL( vv_vs_ne )

PROT_DECL( vs_vv_lt )
PROT_DECL( vs_vv_gt )
PROT_DECL( vs_vv_le )
PROT_DECL( vs_vv_ge )
PROT_DECL( vs_vv_eq )
PROT_DECL( vs_vv_ne )

PROT_DECL( vs_vs_lt )
PROT_DECL( vs_vs_gt )
PROT_DECL( vs_vs_le )
PROT_DECL( vs_vs_ge )
PROT_DECL( vs_vs_eq )
PROT_DECL( vs_vs_ne )

PROT_DECL( ss_vv_lt )
PROT_DECL( ss_vv_gt )
PROT_DECL( ss_vv_le )
PROT_DECL( ss_vv_ge )
PROT_DECL( ss_vv_eq )
PROT_DECL( ss_vv_ne )

PROT_DECL( ss_vs_lt )
PROT_DECL( ss_vs_gt )
PROT_DECL( ss_vs_le )
PROT_DECL( ss_vs_ge )
PROT_DECL( ss_vs_eq )
PROT_DECL( ss_vs_ne )

PROT_DECL( vmaxv )
PROT_DECL( vminv )
PROT_DECL( vmaxi )
PROT_DECL( vmini )
PROT_DECL( vming )
PROT_DECL( vmaxg )
PROT_DECL( vmnmv )
PROT_DECL( vmxmv )
PROT_DECL( vmnmi )
PROT_DECL( vmxmi )
PROT_DECL( vmnmg )
PROT_DECL( vmxmg )
PROT_DECL( vsum )
PROT_DECL( vsm_lt )
PROT_DECL( vsm_gt )
PROT_DECL( vsm_le )
PROT_DECL( vsm_ge )
PROT_DECL( vsm_ne )
PROT_DECL( vsm_eq )
PROT_DECL( vvm_lt )
PROT_DECL( vvm_gt )
PROT_DECL( vvm_le )
PROT_DECL( vvm_ge )
PROT_DECL( vvm_ne )
PROT_DECL( vvm_eq )
PROT_DECL( vscmp )
PROT_DECL( vscmp2 )
PROT_DECL( vcmp )
PROT_DECL( vdot )
PROT_DECL( vrand )

PROT_DECL( vby2li )
PROT_DECL( vin2li )
PROT_DECL( vdi2li )
PROT_DECL( vsp2li )
PROT_DECL( vdp2li )
PROT_DECL( vuby2li )
PROT_DECL( vuin2li )
PROT_DECL( vudi2li )
PROT_DECL( vuli2li )

PROT_DECL( vby2uli )
PROT_DECL( vin2uli )
PROT_DECL( vdi2uli )
PROT_DECL( vli2uli )
PROT_DECL( vsp2uli )
PROT_DECL( vdp2uli )
PROT_DECL( vuby2uli )
PROT_DECL( vuin2uli )
PROT_DECL( vudi2uli )

PROT_DECL( vli2by )
PROT_DECL( vli2in )
PROT_DECL( vli2di )
PROT_DECL( vli2sp )
PROT_DECL( vli2dp )
PROT_DECL( vli2uby )
PROT_DECL( vli2uin )
PROT_DECL( vli2udi )
PROT_DECL( vli2uli )

PROT_DECL( vuli2by )
PROT_DECL( vuli2in )
PROT_DECL( vuli2di )
PROT_DECL( vuli2li )
PROT_DECL( vuli2sp )
PROT_DECL( vuli2dp )
PROT_DECL( vuli2uby )
PROT_DECL( vuli2uin )
PROT_DECL( vuli2udi )

#endif /* undef PROT_DECL */

