#define KERN_PROT_5V( name )		_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_4V_SCAL( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_3V_2SCAL( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_2V_3SCAL( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_3V( name )		_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_CPX_3V( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_2V( name )		_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_2V_MIXED( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_1V_SCAL( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_CPX_1V_SCAL( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_DBM_1S_( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_1V_2SCAL( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_1V_3SCAL( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_2V_SCAL( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_MM( name )		_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_MM_IND( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_MM_NOCC( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_2V_PROJ( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_3V_PROJ( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_VVSLCT( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_VSSLCT( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_SSSLCT( name )	_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_VVMAP( name )		_HOST_TYPED_PROTOTYPE( name , type_code )
#define KERN_PROT_VSMAP( name )		_HOST_TYPED_PROTOTYPE( name , type_code )

#define _HOST_TYPED_PROTOTYPE( name, tc )	HOST_TYPED_PROTOTYPE( name , tc )

