
#define	yymaxdepth vt_maxdepth
#define	yyparse	vt_parse
#define	yylex	vt_lex
#define	yyerror	vt_error
#define	yylval	vt_lval
#define	yychar	vt_char
#define	yydebug	vt_debug
#define	yypact	vt_pact	
#define	yyr1	vt_r1			
#define	yyr2	vt_r2			
#define	yydef	vt_def		
#define	yychk	vt_chk		
#define	yypgo	vt_pgo		
#define	yyact	vt_act		
#define	yyexca	vt_exca
#define yyerrflag vt_errflag
#define yynerrs	vt_nerrs
#define	yyps	vt_ps
#define	yypv	vt_pv
#define	yys	vt_s
#define	yy_yys	vt_yys
#define	yystate	vt_state
#define	yytmp	vt_tmp
#define	yyv	vt_v
#define	yy_yyv	vt_yyv
#define	yyval	vt_val
#define	yylloc	vt_lloc
#define yyreds	vt_reds
#define yytoks	vt_toks
#define yylhs	vt_yylhs
#define yylen	vt_yylen
#define yydefred vt_yydefred
#define yydgoto	vt_yydgoto
#define yysindex vt_yysindex
#define yyrindex vt_yyrindex
#define yygindex vt_yygindex
#define yytable	 vt_yytable
#define yycheck	 vt_yycheck
#define yyname   vt_yyname
#define yyrule   vt_yyrule

