// This file redefines all of the yacc symbols with a prefix
// so that multiple parsers can be linked into the same program.
// This can be obviated by a bison flag argument, but this
// solution may be more portable...

#ifndef YACC_HACK_PREFIX
#error YACC_HACK_PREFIX must be defined
#endif // ! YACC_HACK_PREFIX

#define	yymaxdepth	YYMAXDEPTH_STRING(YACC_HACK_PREFIX)
#define	yyparse		YYPARSE_STRING(YACC_HACK_PREFIX)
#define	yylex		YYLEX_STRING(YACC_HACK_PREFIX)
#define	yyerror		YYERROR_STRING(YACC_HACK_PREFIX)
#define	yylval		YYLVAL_STRING(YACC_HACK_PREFIX)
#define	yychar		YYCHAR_STRING(YACC_HACK_PREFIX)
#define	yydebug		YYDEBUG_STRING(YACC_HACK_PREFIX)
#define	yypact		YYPACT_STRING(YACC_HACK_PREFIX)
#define	yyr1		YYR1_STRING(YACC_HACK_PREFIX)
#define	yyr2		YYR2_STRING(YACC_HACK_PREFIX)
#define	yydef		YYDEF_STRING(YACC_HACK_PREFIX)
#define	yychk		YYCHK_STRING(YACC_HACK_PREFIX)
#define	yypgo		YYPGO_STRING(YACC_HACK_PREFIX)
#define	yyact		YYACT_STRING(YACC_HACK_PREFIX)
#define	yyexca		YYEXCA_STRING(YACC_HACK_PREFIX)
#define yyerrflag	YYERRFLAG(YACC_HACK_PREFIX)
#define yynerrs		YYNERRS_STRING(YACC_HACK_PREFIX)
#define	yyps		YYPS_STRING(YACC_HACK_PREFIX)
#define	yypv		YYPV_STRING(YACC_HACK_PREFIX)
#define	yys		YYS_STRING(YACC_HACK_PREFIX)
#define	yy_yys		YYYYS_STRING(YACC_HACK_PREFIX)
#define	yystate		YYSTATE_STRING(YACC_HACK_PREFIX)
#define	yytmp		YYTMP_STRING(YACC_HACK_PREFIX)
#define	yyv		YYV_STRING(YACC_HACK_PREFIX)
#define	yy_yyv		YYYYV_STRING(YACC_HACK_PREFIX)
#define	yyval		YYVAL_STRING(YACC_HACK_PREFIX)
#define	yylloc		YYLLOC_STRING(YACC_HACK_PREFIX)
#define yyreds		YYREDS_STRING(YACC_HACK_PREFIX)
#define yytoks		YYTOKS_STRING(YACC_HACK_PREFIX)
#define yylhs		YYLHS_STRING(YACC_HACK_PREFIX)
#define yylen		YYLEN_STRING(YACC_HACK_PREFIX)
#define yydefred	YYDEFRED_STRING(YACC_HACK_PREFIX)
#define yydgoto		YYDGOTO_STRING(YACC_HACK_PREFIX)
#define yysindex	YYSINDEX_STRING(YACC_HACK_PREFIX)
#define yyrindex	YYRINDEX_STRING(YACC_HACK_PREFIX)
#define yygindex	YYGINDEX_STRING(YACC_HACK_PREFIX)
#define yytable		YYTABLE_STRING(YACC_HACK_PREFIX)
#define yycheck		YYCHECK_STRING(YACC_HACK_PREFIX)
#define yyname		YNAME_STRING(YACC_HACK_PREFIX)
#define yyrule		YYRULE_STRING(YACC_HACK_PREFIX)

#define YYMAXDEPTH_STRING(p)	_YYMAXDEPTH_STRING(p)
#define YYPARSE_STRING(p)	_YYPARSE_STRING(p)
#define YYLEX_STRING(p)		_YYLEX_STRING(p)
#define YYERROR_STRING(p)	_YYERROR_STRING(p)
#define YYLVAL_STRING(p)	_YYLVAL_STRING(p)
#define YYCHAR_STRING(p)	_YYCHAR_STRING(p)
#define YYDEBUG_STRING(p)	_YYDEBUG_STRING(p)
#define YYPACT_STRING(p)	_YYPACT_STRING(p)
#define YYR1_STRING(p)		_YYR1_STRING(p)
#define YYR2_STRING(p)		_YYR2_STRING(p)
#define YYDEF_STRING(p)		_YYDEF_STRING(p)
#define YYCHK_STRING(p)		_YYCHK_STRING(p)
#define YYPGO_STRING(p)		_YYPGO_STRING(p)
#define YYACT_STRING(p)		_YYACT_STRING(p)
#define YYEXCA_STRING(p)	_YYEXCA_STRING(p)
#define YYERRFLAG_STRING(p)	_YYERRFLAG_STRING(p)
#define YYNERRS_STRING(p)	_YYNERRS_STRING(p)
#define YYPS_STRING(p)		_YYPS_STRING(p)
#define YYPV_STRING(p)		_YYPV_STRING(p)
#define YYS_STRING(p)		_YYS_STRING(p)
#define YYYYS_STRING(p)		_YYYYS_STRING(p)
#define YYSTATE_STRING(p)	_YYSTATE_STRING(p)
#define YYTMP_STRING(p)		_YYTMP_STRING(p)
#define YYV_STRING(p)		_YYV_STRING(p)
#define YYYYV_STRING(p)		_YYYYV_STRING(p)
#define YYVAL_STRING(p)		_YYVAL_STRING(p)
#define YYLLOC_STRING(p)	_YYLLOC_STRING(p)
#define YYREDS_STRING(p)	_YYREDS_STRING(p)
#define YYTOKS_STRING(p)	_YYTOKS_STRING(p)
#define YYLHS_STRING(p)		_YYLHS_STRING(p)
#define YYLEN_STRING(p)		_YYLEN_STRING(p)
#define YYDEFRED(p)		_YYDEFRED(p)
#define YYDGOTO_STRING(p)	_YYDGOTO_STRING(p)
#define YYSINDEX_STRING(p)	_YYSINDEX_STRING(p)
#define YYRINDEX_STRING(p)	_YYRINDEX_STRING(p)
#define YYGINDEX_STRING(p)	_YYGINDEX_STRING(p)
#define YYTABLE_STRING(p)	_YYTABLE_STRING(p)
#define YYCHECK_STRING(p)	_YYCHECK_STRING(p)
#define YYNAME_STRING(p)	_YYNAME_STRING(p)
#define YYRULE_STRING(p)	_YYRULE_STRING(p)


#define _YYMAXDEPTH_STRING(p)	__YYMAXDEPTH_STRING(p)
#define _YYPARSE_STRING(p)	__YYPARSE_STRING(p)
#define _YYLEX_STRING(p)	__YYLEX_STRING(p)
#define _YYERROR_STRING(p)	__YYERROR_STRING(p)
#define _YYLVAL_STRING(p)	__YYLVAL_STRING(p)
#define _YYCHAR_STRING(p)	__YYCHAR_STRING(p)
#define _YYDEBUG_STRING(p)	__YYDEBUG_STRING(p)
#define _YYPACT_STRING(p)	__YYPACT_STRING(p)
#define _YYR1_STRING(p)		__YYR1_STRING(p)
#define _YYR2_STRING(p)		__YYR2_STRING(p)
#define _YYDEF_STRING(p)	__YYDEF_STRING(p)
#define _YYCHK_STRING(p)	__YYCHK_STRING(p)
#define _YYPGO_STRING(p)	__YYPGO_STRING(p)
#define _YYACT_STRING(p)	__YYACT_STRING(p)
#define _YYEXCA_STRING(p)	__YYEXCA_STRING(p)
#define _YYERRFLAG_STRING(p)	__YYERRFLAG_STRING(p)
#define _YYNERRS_STRING(p)	__YYNERRS_STRING(p)
#define _YYPS_STRING(p)		__YYPS_STRING(p)
#define _YYPV_STRING(p)		__YYPV_STRING(p)
#define _YYS_STRING(p)		__YYS_STRING(p)
#define _YYYYS_STRING(p)	__YYYYS_STRING(p)
#define _YYSTATE_STRING(p)	__YYSTATE_STRING(p)
#define _YYTMP_STRING(p)	__YYTMP_STRING(p)
#define _YYV_STRING(p)		__YYV_STRING(p)
#define _YYYYV_STRING(p)	__YYYYV_STRING(p)
#define _YYVAL_STRING(p)	__YYVAL_STRING(p)
#define _YYLLOC_STRING(p)	__YYLLOC_STRING(p)
#define _YYREDS_STRING(p)	__YYREDS_STRING(p)
#define _YYTOKS_STRING(p)	__YYTOKS_STRING(p)
#define _YYLHS_STRING(p)	__YYLHS_STRING(p)
#define _YYLEN_STRING(p)	__YYLEN_STRING(p)
#define _YYDEFRED(p)		__YYDEFRED(p)
#define _YYDGOTO_STRING(p)	__YYDGOTO_STRING(p)
#define _YYSINDEX_STRING(p)	__YYSINDEX_STRING(p)
#define _YYRINDEX_STRING(p)	__YYRINDEX_STRING(p)
#define _YYGINDEX_STRING(p)	__YYGINDEX_STRING(p)
#define _YYTABLE_STRING(p)	__YYTABLE_STRING(p)
#define _YYCHECK_STRING(p)	__YYCHECK_STRING(p)
#define _YYNAME_STRING(p)	__YYNAME_STRING(p)
#define _YYRULE_STRING(p)	__YYRULE_STRING(p)


#define __YYMAXDEPTH_STRING(p)	p##_maxdepth
#define __YYPARSE_STRING(p)	p##_parse
#define __YYLEX_STRING(p)	p##_lex
#define __YYERROR_STRING(p)	p##_error
#define __YYLVAL_STRING(p)	p##_lval
#define __YYCHAR_STRING(p)	p##_char
#define __YYDEBUG_STRING(p)	p##_debug
#define __YYPACT_STRING(p)	p##_pact
#define __YYR1_STRING(p)	p##_r1
#define __YYR2_STRING(p)	p##_r2
#define __YYDEF_STRING(p)	p##_def
#define __YYCHK_STRING(p)	p##_chk
#define __YYPGO_STRING(p)	p##_pgo
#define __YYACT_STRING(p)	p##_act
#define __YYEXCA_STRING(p)	p##_exca
#define __YYERRFLAG_STRING(p)	p##_errflag
#define __YYNERRS_STRING(p)	p##_nerrs
#define __YYPS_STRING(p)	p##_ps
#define __YYPV_STRING(p)	p##_pv
#define __YYS_STRING(p)		p##_s
#define __YYYYS_STRING(p)	p##_yys
#define __YYSTATE_STRING(p)	p##_state
#define __YYTMP_STRING(p)	p##_tmp
#define __YYV_STRING(p)		p##_v
#define __YYYYV_STRING(p)	p##_yyv
#define __YYVAL_STRING(p)	p##_val
#define __YYLLOC_STRING(p)	p##_lloc
#define __YYREDS_STRING(p)	p##_reds
#define __YYTOKS_STRING(p)	p##_toks
#define __YYLHS_STRING(p)	p##_yylhs
#define __YYLEN_STRING(p)	p##_yylen
#define __YYDEFRED(p)		p##_yydefred
#define __YYDGOTO_STRING(p)	p##_yydgoto
#define __YYSINDEX_STRING(p)	p##_yysindex
#define __YYRINDEX_STRING(p)	p##_yyrindex
#define __YYGINDEX_STRING(p)	p##_yygindex
#define __YYTABLE_STRING(p)	p##_yytable
#define __YYCHECK_STRING(p)	p##_yycheck
#define __YYNAME_STRING(p)	p##_yyname
#define __YYRULE_STRING(p)	p##_yyrule
