// Declare increments

// Now we set the increments in the vector_args struct?

#define DECL_EQSP_INCRS_1	/*int dst_incr;*/
#define DECL_EQSP_INCRS_SRC1	/*int s1_incr;*/
#define DECL_EQSP_INCRS_SRC2	/*int s2_incr;*/
#define DECL_EQSP_INCRS_SRC3	/*int s3_incr;*/
#define DECL_EQSP_INCRS_SRC4	/*int s4_incr;*/
#define DECL_EQSP_INCRS_SBM	/*int sbm_incr;*/
#define DECL_EQSP_INCRS_DBM	/*int dbm_incr;*/
#define DECL_EQSP_INCRS_DBM_SBM	/*int dbm_incr;*/
#define DECL_EQSP_INCRS_2	DECL_EQSP_INCRS_1 DECL_EQSP_INCRS_SRC1
#define DECL_EQSP_INCRS_CONV	DECL_EQSP_INCRS_1 DECL_EQSP_INCRS_SRC1
#define DECL_EQSP_INCRS_3	DECL_EQSP_INCRS_2 DECL_EQSP_INCRS_SRC2
#define DECL_EQSP_INCRS_4	DECL_EQSP_INCRS_3 DECL_EQSP_INCRS_SRC3
#define DECL_EQSP_INCRS_5	DECL_EQSP_INCRS_4 DECL_EQSP_INCRS_SRC4
#define DECL_EQSP_INCRS_2SRCS	DECL_EQSP_INCRS_SRC1 DECL_EQSP_INCRS_SRC2

#define DECL_EQSP_INCRS_SBM_1	DECL_EQSP_INCRS_1 DECL_EQSP_INCRS_SBM
#define DECL_EQSP_INCRS_SBM_2	DECL_EQSP_INCRS_2 DECL_EQSP_INCRS_SBM
#define DECL_EQSP_INCRS_SBM_3	DECL_EQSP_INCRS_3 DECL_EQSP_INCRS_SBM
#define DECL_EQSP_INCRS_DBM_		DECL_EQSP_INCRS_DBM
#define DECL_EQSP_INCRS_DBM_1SRC	DECL_EQSP_INCRS_SRC1 DECL_EQSP_INCRS_DBM
#define DECL_EQSP_INCRS_DBM_2SRCS	DECL_EQSP_INCRS_2SRCS DECL_EQSP_INCRS_DBM

