#ifndef _GPU_ARGS_H_
#define _GPU_ARGS_H_

#include "veclib/gen_kern_args.h"
//#include "veclib/dim3.h"
#include "veclib/dim5.h"

/* These are the arguments used in the declarations
 * of the kernel functions: DECLARE_KERN_ARGS_FAST_2 etc
 * When we call the kernel (cuda), we use KERN_ARGS_FAST_2,
 * and when we pass them one-by-one (openCL) we use SET_KERNEL_ARGS_2
 *
 * Really, we need macros to declare macros!?
 */

#ifdef BUILD_FOR_OPENCL
#define KERNEL_ARG_QUALIFIER	__global
#else // ! BUILD_FOR_OPENCL
#define KERNEL_ARG_QUALIFIER
#endif // ! BUILD_FOR_OPENCL

/******************* declarations and calling kernel arguments  ***************************/
/* used to be VFUNC_ARGS (for declarations), changed to DECLARE_KERN_ARGS */ 
// Special cases


#define KERN_ARGS_NOCC_HELPER					\
								\
	dst_extrema,		\
	dst_counts,		\
	src_vals,		\
	src_counts,		\
	dst_indices,		\
	len1, len2, stride

// BUG - how can we insure that the declarations are consistent!?

#define DECLARE_KERN_ARGS_NOCC_HELPER				\
								\
	KERNEL_ARG_QUALIFIER std_type* dst_extrema,		\
	KERNEL_ARG_QUALIFIER index_type* dst_counts,		\
	KERNEL_ARG_QUALIFIER std_type* src_vals,		\
	KERNEL_ARG_QUALIFIER index_type *src_counts,		\
	KERNEL_ARG_QUALIFIER index_type *dst_indices,		\
	DECLARE_2_LENGTHS					\
	, uint32_t stride



#define KERN_ARGS_NOCC_SETUP					\
								\
	dst_extrema,						\
	dst_counts,						\
	src_vals,						\
	dst_indices,						\
	len1, len2


#define DECLARE_KERN_ARGS_NOCC_SETUP				\
								\
	KERNEL_ARG_QUALIFIER std_type* dst_extrema,		\
	KERNEL_ARG_QUALIFIER index_type* dst_counts,		\
	KERNEL_ARG_QUALIFIER std_type* src_vals,		\
	KERNEL_ARG_QUALIFIER index_type *dst_indices,		\
	DECLARE_2_LENGTHS


// MM_ARGS or helper args?
/*#define KERN_ARGS_MM	dest,s1,s2,len1,len2*/

#define KERN_ARGS_MM						\
								\
	a,			\
	b,			\
	c,			\
	len1, len2


#define DECLARE_KERN_ARGS_MM					\
								\
	KERNEL_ARG_QUALIFIER std_type* a,			\
	KERNEL_ARG_QUALIFIER std_type* b,			\
	KERNEL_ARG_QUALIFIER std_type* c,			\
	DECLARE_2_LENGTHS

#define DECLARE_2_LENGTHS					\
	uint32_t len1, uint32_t len2

#define KERN_ARGS_2V_PROJ	dest, s1, len1, len2

#define DECLARE_KERN_ARGS_2V_PROJ				\
								\
	KERNEL_ARG_QUALIFIER std_type* dest,			\
	KERNEL_ARG_QUALIFIER std_type* s1,			\
	DECLARE_2_LENGTHS

#define DECLARE_KERN_ARGS_CPX_2V_PROJ				\
								\
	KERNEL_ARG_QUALIFIER std_cpx* dest,			\
	KERNEL_ARG_QUALIFIER std_cpx* s1,			\
	DECLARE_2_LENGTHS

#define DECLARE_KERN_ARGS_QUAT_2V_PROJ				\
								\
	KERNEL_ARG_QUALIFIER std_quat* dest,			\
	KERNEL_ARG_QUALIFIER std_quat* s1,			\
	DECLARE_2_LENGTHS

#define KERN_ARGS_IDX_SETUP	indices,s1,s2,len1,len2

#define DECLARE_KERN_ARGS_IDX_SETUP				\
								\
	KERNEL_ARG_QUALIFIER index_type* a,			\
	KERNEL_ARG_QUALIFIER std_type* b,			\
	KERNEL_ARG_QUALIFIER std_type* c,			\
	DECLARE_2_LENGTHS


#define DECLARE_KERN_ARGS_2V_PROJ_IDX_HELPER			\
								\
	KERNEL_ARG_QUALIFIER index_type* a,			\
	KERNEL_ARG_QUALIFIER index_type* b,			\
	KERNEL_ARG_QUALIFIER index_type* c,			\
	KERNEL_ARG_QUALIFIER std_type *orig,			\
	DECLARE_2_LENGTHS


#define DECLARE_KERN_ARGS_2V_PROJ				\
								\
	KERNEL_ARG_QUALIFIER std_type* dest,			\
	KERNEL_ARG_QUALIFIER std_type* s1,			\
	DECLARE_2_LENGTHS


#define KERN_ARGS_3V_PROJ					\
								\
	dest,			\
	s1,			\
	s2,			\
	len1, len2



#define DECLARE_KERN_ARGS_3V_PROJ				\
								\
	KERNEL_ARG_QUALIFIER std_type* dest,			\
	KERNEL_ARG_QUALIFIER std_type* s1,			\
	KERNEL_ARG_QUALIFIER std_type* s2,			\
	DECLARE_2_LENGTHS


#define DECLARE_KERN_ARGS_CPX_3V_PROJ				\
								\
	KERNEL_ARG_QUALIFIER std_cpx* dest,			\
	KERNEL_ARG_QUALIFIER std_cpx* s1,			\
	KERNEL_ARG_QUALIFIER std_cpx* s2,			\
	DECLARE_2_LENGTHS

// is this a special case???
#define DECLARE_KERN_ARGS_DBM_GPU_INFO				\
								\
	KERNEL_ARG_QUALIFIER Bitmap_GPU_Info * dbm_info_p

////////////// end of special cases

////////////// generic args for kernel declaration

// BUG?  we ran into problems with vector-scalar ops and spdp mixed precision type,
// because of inconsistency between the cpu kernel (which assumed std_type)
// and the arg fetching code (which assumed dest_type).  We tried fixing that
// by switching the kernel to use dest_type, but that broke vsatan2 (cuda),
// and doesn't make sense anyway...

#define DECLARE_KERN_ARGS_1S		std_type scalar1_val
#define DECLARE_KERN_ARGS_2S		DECLARE_KERN_ARGS_1S, std_type scalar2_val
#define DECLARE_KERN_ARGS_3S		DECLARE_KERN_ARGS_2S, std_type scalar3_val
//#define DECLARE_KERN_ARGS_1S		dest_type scalar1_val
//#define DECLARE_KERN_ARGS_2S		DECLARE_KERN_ARGS_1S, dest_type scalar2_val
//#define DECLARE_KERN_ARGS_3S		DECLARE_KERN_ARGS_2S, dest_type scalar3_val

#define DECLARE_KERN_ARGS_CPX_1S	std_cpx cscalar1_val
#define DECLARE_KERN_ARGS_CPX_2S	DECLARE_KERN_ARGS_CPX_1S , std_cpx cscalar2_val
//#define DECLARE_KERN_ARGS_CPX_1S	dest_cpx cscalar1_val
//#define DECLARE_KERN_ARGS_CPX_2S	DECLARE_KERN_ARGS_CPX_1S , dest_cpx cscalar2_val

#define DECLARE_KERN_ARGS_QUAT_1S	std_quat qscalar1_val
#define DECLARE_KERN_ARGS_QUAT_2S	DECLARE_KERN_ARGS_QUAT_1S , std_quat qscalar2_val
//#define DECLARE_KERN_ARGS_QUAT_1S	dest_quat qscalar1_val
//#define DECLARE_KERN_ARGS_QUAT_2S	DECLARE_KERN_ARGS_QUAT_1S , dest_quat qscalar2_val

#ifdef BUILD_FOR_OPENCL

// BUG?  should these offsets be larger than int?
#define DECLARE_KERN_ARGS_DEST_OFFSET		OCL_OFFSET_TYPE a_offset 
#define DECLARE_KERN_ARGS_SRC1_OFFSET		OCL_OFFSET_TYPE b_offset 
#define DECLARE_KERN_ARGS_SRC2_OFFSET		OCL_OFFSET_TYPE c_offset 
#define DECLARE_KERN_ARGS_SRC3_OFFSET		OCL_OFFSET_TYPE d_offset 
#define DECLARE_KERN_ARGS_SRC4_OFFSET		OCL_OFFSET_TYPE e_offset 
#define DECLARE_KERN_ARGS_SBM_OFFSET		OCL_OFFSET_TYPE sbm_offset 
#define DECLARE_KERN_ARGS_DBM_OFFSET		OCL_OFFSET_TYPE dbm_offset 
// BUG?  offsets for bitmaps?

#else // ! BUILD_FOR_OPENCL

#define DECLARE_KERN_ARGS_DEST_OFFSET
#define DECLARE_KERN_ARGS_SRC1_OFFSET
#define DECLARE_KERN_ARGS_SRC2_OFFSET
#define DECLARE_KERN_ARGS_SRC3_OFFSET
#define DECLARE_KERN_ARGS_SRC4_OFFSET

#endif // ! BUILD_FOR_OPENCL

#define DECLARE_KERN_ARGS_SLOW_SIZE		dim5 szarr
#define DECLARE_KERN_ARGS_SLOW_SIZE_OFFSET	/* nop */

#define DECLARE_KERN_ARGS_FAST_CONV_DEST(type)	KERNEL_ARG_QUALIFIER type* a
#define DECLARE_KERN_ARGS_FAST_1   	KERNEL_ARG_QUALIFIER dest_type* a
#define DECLARE_KERN_ARGS_FAST_SRC1	KERNEL_ARG_QUALIFIER std_type* b
#define DECLARE_KERN_ARGS_FAST_SRC2	KERNEL_ARG_QUALIFIER std_type* c
#define DECLARE_KERN_ARGS_FAST_SRC3	KERNEL_ARG_QUALIFIER std_type* d
#define DECLARE_KERN_ARGS_FAST_SRC4	KERNEL_ARG_QUALIFIER std_type* e

// complex stuff

#define DECLARE_KERN_ARGS_FAST_CPX_1		KERNEL_ARG_QUALIFIER dest_cpx* a
#define DECLARE_KERN_ARGS_FAST_CPX_SRC1 	KERNEL_ARG_QUALIFIER std_cpx* b
#define DECLARE_KERN_ARGS_FAST_CPX_SRC2 	KERNEL_ARG_QUALIFIER std_cpx* c
#define DECLARE_KERN_ARGS_FAST_CPX_SRC3 	KERNEL_ARG_QUALIFIER std_cpx* d
#define DECLARE_KERN_ARGS_FAST_CPX_SRC4 	KERNEL_ARG_QUALIFIER std_cpx* e

// quaternion stuff

#define DECLARE_KERN_ARGS_FAST_QUAT_1		KERNEL_ARG_QUALIFIER dest_quat* a
#define DECLARE_KERN_ARGS_FAST_QUAT_SRC1	KERNEL_ARG_QUALIFIER std_quat* b
#define DECLARE_KERN_ARGS_FAST_QUAT_SRC2	KERNEL_ARG_QUALIFIER std_quat* c
#define DECLARE_KERN_ARGS_FAST_QUAT_SRC3	KERNEL_ARG_QUALIFIER std_quat* d
#define DECLARE_KERN_ARGS_FAST_QUAT_SRC4	KERNEL_ARG_QUALIFIER std_quat* e


// EQSP real

#define DECLARE_KERN_ARGS_EQSP_INC1	int inc1
#define DECLARE_KERN_ARGS_EQSP_INC2	int inc2
#define DECLARE_KERN_ARGS_EQSP_INC3	int inc3
#define DECLARE_KERN_ARGS_EQSP_INC4	int inc4
#define DECLARE_KERN_ARGS_EQSP_INC5	int inc5

// real, slow


#define DECLARE_KERN_ARGS_SLOW_INC1	GPU_INDEX_TYPE inc1
#define DECLARE_KERN_ARGS_SLOW_INC2	GPU_INDEX_TYPE inc2
#define DECLARE_KERN_ARGS_SLOW_INC3	GPU_INDEX_TYPE inc3
#define DECLARE_KERN_ARGS_SLOW_INC4	GPU_INDEX_TYPE inc4
#define DECLARE_KERN_ARGS_SLOW_INC5	GPU_INDEX_TYPE inc5

#define DECLARE_KERN_ARGS_FAST_LEN	int len
#define DECLARE_KERN_ARGS_EQSP_LEN	int len
//#define DECLARE_KERN_ARGS_SLOW_LEN	GPU_INDEX_TYPE xyz_len	// BUG vwxyz_len
#define DECLARE_KERN_ARGS_SLOW_LEN	GPU_INDEX_TYPE vwxyz_len

#define DECLARE_KERN_ARGS_FAST_SBM	KERNEL_ARG_QUALIFIER bitmap_word *sbm , int sbm_bit0
#define DECLARE_KERN_ARGS_EQSP_SBM	KERNEL_ARG_QUALIFIER bitmap_word *sbm , int sbm_bit0 , int sbm_inc
#define DECLARE_KERN_ARGS_SLOW_SBM	KERNEL_ARG_QUALIFIER bitmap_word *sbm , int sbm_bit0 , GPU_INDEX_TYPE sbm_inc


//#define DECLARE_KERN_ARGS_FAST_DBM	KERNEL_ARG_QUALIFIER bitmap_word *dbm , int dbm_bit0
//#define DECLARE_KERN_ARGS_EQSP_DBM	KERNEL_ARG_QUALIFIER bitmap_word *dbm , int dbm_bit0 , int dbm_inc
//#define DECLARE_KERN_ARGS_SLOW_DBM	KERNEL_ARG_QUALIFIER bitmap_word *dbm , int dbm_bit0 , GPU_INDEX_TYPE dbm_inc
#define DECLARE_KERN_ARGS_FAST_DBM	KERNEL_ARG_QUALIFIER bitmap_word *dbm
#define DECLARE_KERN_ARGS_EQSP_DBM	KERNEL_ARG_QUALIFIER bitmap_word *dbm
#define DECLARE_KERN_ARGS_SLOW_DBM	KERNEL_ARG_QUALIFIER bitmap_word *dbm

/****************************************/

#define DECLARE_KERN_ARGS_FAST_CONV(to_type)	GEN_ARGS_FAST_CONV(DECLARE_KERN_ARGS,to_type)

#define DECLARE_KERN_ARGS_FAST_2	GEN_ARGS_FAST_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_3	GEN_ARGS_FAST_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_4	GEN_ARGS_FAST_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_5	GEN_ARGS_FAST_5(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_1SRC	GEN_ARGS_FAST_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_2SRCS	GEN_ARGS_FAST_2SRCS(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FAST_CPX_2	GEN_ARGS_FAST_CPX_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_RC_2	GEN_ARGS_FAST_RC_2(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FAST_CPX_3	GEN_ARGS_FAST_CPX_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_CPX_4	GEN_ARGS_FAST_CPX_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_CPX_5	GEN_ARGS_FAST_CPX_5(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_CCR_3	GEN_ARGS_FAST_CCR_3(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FAST_CR_1S_2	GEN_ARGS_FAST_CR_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_CPX_1S_2	GEN_ARGS_FAST_CPX_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_CPX_1S_1	GEN_ARGS_FAST_CPX_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_CPX_2S_1	GEN_ARGS_FAST_CPX_2S_1(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FAST_QUAT_2	GEN_ARGS_FAST_QUAT_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_QUAT_3	GEN_ARGS_FAST_QUAT_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_QUAT_4	GEN_ARGS_FAST_QUAT_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_QUAT_5	GEN_ARGS_FAST_QUAT_5(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_QQR_3	GEN_ARGS_FAST_QQR_3(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FAST_QR_1S_2		GEN_ARGS_FAST_QR_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_QUAT_1S_2	GEN_ARGS_FAST_QUAT_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_QUAT_1S_1	GEN_ARGS_FAST_QUAT_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_QUAT_2S_1	GEN_ARGS_FAST_QUAT_2S_1(DECLARE_KERN_ARGS)

/////////////////////////////

#define DECLARE_KERN_ARGS_EQSP_1SRC	GEN_ARGS_EQSP_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_2SRCS	GEN_ARGS_EQSP_2SRCS(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_CONV(to_type)	GEN_ARGS_EQSP_CONV(DECLARE_KERN_ARGS,to_type)
#define DECLARE_KERN_ARGS_EQSP_2	GEN_ARGS_EQSP_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_3	GEN_ARGS_EQSP_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_4	GEN_ARGS_EQSP_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_5	GEN_ARGS_EQSP_5(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_EQSP_CPX_1SRC		GEN_ARGS_EQSP_CPX_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_CPX_2SRCS	GEN_ARGS_EQSP_CPX_2SRCS(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_CPX_2		GEN_ARGS_EQSP_CPX_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_CPX_3		GEN_ARGS_EQSP_CPX_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_CPX_4		GEN_ARGS_EQSP_CPX_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_CPX_5		GEN_ARGS_EQSP_CPX_5(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_EQSP_CCR_3		GEN_ARGS_EQSP_CCR_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_RC_2		GEN_ARGS_EQSP_RC_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_CR_1S_2		GEN_ARGS_EQSP_CR_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_CPX_1S_2		GEN_ARGS_EQSP_CPX_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_CPX_1S_1		GEN_ARGS_EQSP_CPX_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_CPX_2S_1		GEN_ARGS_EQSP_CPX_2S_1(DECLARE_KERN_ARGS)

// quaternion, eqsp

#define DECLARE_KERN_ARGS_EQSP_QUAT_1SRC	GEN_ARGS_EQSP_QUAT_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_QUAT_2SRCS	GEN_ARGS_EQSP_QUAT_2SRCS(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_QUAT_2		GEN_ARGS_EQSP_QUAT_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_QUAT_3		GEN_ARGS_EQSP_QUAT_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_QUAT_4		GEN_ARGS_EQSP_QUAT_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_QUAT_5		GEN_ARGS_EQSP_QUAT_5(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_EQSP_QQR_3		GEN_ARGS_EQSP_QQR_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_RQ_2		GEN_ARGS_EQSP_RQ_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_QR_1S_2		GEN_ARGS_EQSP_QR_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_QUAT_1S_2	GEN_ARGS_EQSP_QUAT_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_QUAT_1S_1	GEN_ARGS_EQSP_QUAT_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_QUAT_2S_1	GEN_ARGS_EQSP_QUAT_2S_1(DECLARE_KERN_ARGS)

////////////////////////////////////////

#define DECLARE_KERN_ARGS_SLOW_CONV(t)	GEN_ARGS_SLOW_CONV(DECLARE_KERN_ARGS,t)
#define DECLARE_KERN_ARGS_SLOW_2	GEN_ARGS_SLOW_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_3	GEN_ARGS_SLOW_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_4	GEN_ARGS_SLOW_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_5	GEN_ARGS_SLOW_5(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_SLOW_CPX_2	GEN_ARGS_SLOW_CPX_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_CPX_3	GEN_ARGS_SLOW_CPX_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_CPX_4	GEN_ARGS_SLOW_CPX_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_CPX_5	GEN_ARGS_SLOW_CPX_5(DECLARE_KERN_ARGS)


#define DECLARE_KERN_ARGS_SLOW_CCR_3		GEN_ARGS_SLOW_CCR_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_RC_2		GEN_ARGS_SLOW_RC_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_CR_1S_2		GEN_ARGS_SLOW_CR_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_CPX_1S_2	GEN_ARGS_SLOW_CPX_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_CPX_1S_1	GEN_ARGS_SLOW_CPX_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_CPX_2S_1	GEN_ARGS_SLOW_CPX_2S_1(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_SLOW_QUAT_2	GEN_ARGS_SLOW_QUAT_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_QUAT_3	GEN_ARGS_SLOW_QUAT_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_QUAT_4	GEN_ARGS_SLOW_QUAT_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_QUAT_5	GEN_ARGS_SLOW_QUAT_5(DECLARE_KERN_ARGS)


#define DECLARE_KERN_ARGS_SLOW_QQR_3		GEN_ARGS_SLOW_QQR_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_RQ_2		GEN_ARGS_SLOW_RQ_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_QR_1S_2		GEN_ARGS_SLOW_QR_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_QUAT_1S_2	GEN_ARGS_SLOW_QUAT_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_QUAT_1S_1	GEN_ARGS_SLOW_QUAT_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_QUAT_2S_1	GEN_ARGS_SLOW_QUAT_2S_1(DECLARE_KERN_ARGS)

////////////////

#define DECLARE_KERN_ARGS_SLOW_1SRC	GEN_ARGS_SLOW_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_2SRCS	GEN_ARGS_SLOW_2SRCS(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FLEN_CONV(t)	GEN_ARGS_FLEN_CONV(DECLARE_KERN_ARGS,t)
#define DECLARE_KERN_ARGS_FLEN_1	GEN_ARGS_FLEN_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_2	GEN_ARGS_FLEN_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_3	GEN_ARGS_FLEN_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_4	GEN_ARGS_FLEN_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_5	GEN_ARGS_FLEN_5(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_ELEN_CONV(t)	GEN_ARGS_ELEN_CONV(DECLARE_KERN_ARGS,t)
#define DECLARE_KERN_ARGS_ELEN_1	GEN_ARGS_ELEN_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_2	GEN_ARGS_ELEN_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_3	GEN_ARGS_ELEN_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_4	GEN_ARGS_ELEN_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_5	GEN_ARGS_ELEN_5(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_SLEN_CONV(t)	GEN_ARGS_SLEN_CONV(DECLARE_KERN_ARGS,t)
#define DECLARE_KERN_ARGS_SLEN_1	GEN_ARGS_SLEN_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_2	GEN_ARGS_SLEN_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_3	GEN_ARGS_SLEN_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_4	GEN_ARGS_SLEN_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_5	GEN_ARGS_SLEN_5(DECLARE_KERN_ARGS)

// complex, with len

#define DECLARE_KERN_ARGS_FLEN_CPX_1	GEN_ARGS_FLEN_CPX_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_CPX_2	GEN_ARGS_FLEN_CPX_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_CPX_3	GEN_ARGS_FLEN_CPX_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_CPX_4	GEN_ARGS_FLEN_CPX_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_CPX_5	GEN_ARGS_FLEN_CPX_5(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_ELEN_CPX_1	GEN_ARGS_ELEN_CPX_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_CPX_2	GEN_ARGS_ELEN_CPX_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_CPX_3	GEN_ARGS_ELEN_CPX_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_CPX_4	GEN_ARGS_ELEN_CPX_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_CPX_5	GEN_ARGS_ELEN_CPX_5(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_SLEN_CPX_1	GEN_ARGS_SLEN_CPX_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_CPX_2	GEN_ARGS_SLEN_CPX_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_CPX_3	GEN_ARGS_SLEN_CPX_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_CPX_4	GEN_ARGS_SLEN_CPX_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_CPX_5	GEN_ARGS_SLEN_CPX_5(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FLEN_RC_2	GEN_ARGS_FLEN_RC_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_RC_2	GEN_ARGS_ELEN_RC_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_RC_2	GEN_ARGS_SLEN_RC_2(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FLEN_CCR_3	GEN_ARGS_FLEN_CCR_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_CCR_3	GEN_ARGS_ELEN_CCR_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_CCR_3	GEN_ARGS_SLEN_CCR_3(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FLEN_CR_1S_2	GEN_ARGS_FLEN_CR_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_CR_1S_2	GEN_ARGS_ELEN_CR_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_CR_1S_2	GEN_ARGS_SLEN_CR_1S_2(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FLEN_CPX_1S_2	GEN_ARGS_FLEN_CPX_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_CPX_1S_2	GEN_ARGS_ELEN_CPX_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_CPX_1S_2	GEN_ARGS_SLEN_CPX_1S_2(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FLEN_CPX_1S_1	GEN_ARGS_FLEN_CPX_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_CPX_1S_1	GEN_ARGS_ELEN_CPX_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_CPX_1S_1	GEN_ARGS_SLEN_CPX_1S_1(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FLEN_CPX_2S_1	GEN_ARGS_FLEN_CPX_2S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_CPX_2S_1	GEN_ARGS_ELEN_CPX_2S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_CPX_2S_1	GEN_ARGS_SLEN_CPX_2S_1(DECLARE_KERN_ARGS)

// quaternion, with len

#define DECLARE_KERN_ARGS_FLEN_QUAT_1	GEN_ARGS_FLEN_QUAT_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_QUAT_2	GEN_ARGS_FLEN_QUAT_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_QUAT_3	GEN_ARGS_FLEN_QUAT_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_QUAT_4	GEN_ARGS_FLEN_QUAT_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_QUAT_5	GEN_ARGS_FLEN_QUAT_5(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_ELEN_QUAT_1	GEN_ARGS_ELEN_QUAT_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_QUAT_2	GEN_ARGS_ELEN_QUAT_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_QUAT_3	GEN_ARGS_ELEN_QUAT_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_QUAT_4	GEN_ARGS_ELEN_QUAT_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_QUAT_5	GEN_ARGS_ELEN_QUAT_5(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_SLEN_QUAT_1	GEN_ARGS_SLEN_QUAT_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_QUAT_2	GEN_ARGS_SLEN_QUAT_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_QUAT_3	GEN_ARGS_SLEN_QUAT_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_QUAT_4	GEN_ARGS_SLEN_QUAT_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_QUAT_5	GEN_ARGS_SLEN_QUAT_5(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FLEN_RQ_2		GEN_ARGS_FLEN_RQ_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_QQR_3		GEN_ARGS_FLEN_QQR_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_QR_1S_2		GEN_ARGS_FLEN_QR_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_QUAT_1S_2	GEN_ARGS_FLEN_QUAT_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_QUAT_1S_1	GEN_ARGS_FLEN_QUAT_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_QUAT_2S_1	GEN_ARGS_FLEN_QUAT_2S_1(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_ELEN_RQ_2		GEN_ARGS_ELEN_RQ_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_QQR_3		GEN_ARGS_ELEN_QQR_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_QR_1S_2		GEN_ARGS_ELEN_QR_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_QUAT_1S_2	GEN_ARGS_ELEN_QUAT_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_QUAT_1S_1	GEN_ARGS_ELEN_QUAT_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_QUAT_2S_1	GEN_ARGS_ELEN_QUAT_2S_1(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_SLEN_RQ_2		GEN_ARGS_SLEN_RQ_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_QQR_3		GEN_ARGS_SLEN_QQR_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_QR_1S_2		GEN_ARGS_SLEN_QR_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_QUAT_1S_2	GEN_ARGS_SLEN_QUAT_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_QUAT_1S_1	GEN_ARGS_SLEN_QUAT_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_QUAT_2S_1	GEN_ARGS_SLEN_QUAT_2S_1(DECLARE_KERN_ARGS)

//////////////////////////

#define DECLARE_KERN_ARGS_FAST_1S_1	GEN_ARGS_FAST_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_1S_2	GEN_ARGS_FAST_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_1S_4	GEN_ARGS_FAST_1S_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_2S_1	GEN_ARGS_FAST_2S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_2S_3	GEN_ARGS_FAST_2S_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_3S_2	GEN_ARGS_FAST_3S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_3S_1	GEN_ARGS_FAST_3S_1(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_EQSP_1S_1	GEN_ARGS_EQSP_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_1S_2	GEN_ARGS_EQSP_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_1S_4	GEN_ARGS_EQSP_1S_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_2S_1	GEN_ARGS_EQSP_2S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_2S_3	GEN_ARGS_EQSP_2S_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_3S_2	GEN_ARGS_EQSP_3S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_3S_1	GEN_ARGS_EQSP_3S_1(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_SLOW_1S_1	GEN_ARGS_SLOW_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_1S_2	GEN_ARGS_SLOW_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_1S_4	GEN_ARGS_SLOW_1S_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_2S_1	GEN_ARGS_SLOW_2S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_2S_3	GEN_ARGS_SLOW_2S_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_3S_2	GEN_ARGS_SLOW_3S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_3S_1	GEN_ARGS_SLOW_3S_1(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_FLEN_1S_1	GEN_ARGS_FLEN_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_1S_2	GEN_ARGS_FLEN_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_1S_4	GEN_ARGS_FLEN_1S_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_2S_1	GEN_ARGS_FLEN_2S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_2S_3	GEN_ARGS_FLEN_2S_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_3S_2	GEN_ARGS_FLEN_3S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_3S_1	GEN_ARGS_FLEN_3S_1(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_ELEN_1S_1	GEN_ARGS_ELEN_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_1S_2	GEN_ARGS_ELEN_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_1S_4	GEN_ARGS_ELEN_1S_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_2S_1	GEN_ARGS_ELEN_2S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_2S_3	GEN_ARGS_ELEN_2S_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_3S_2	GEN_ARGS_ELEN_3S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_3S_1	GEN_ARGS_ELEN_3S_1(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_SLEN_1S_1	GEN_ARGS_SLEN_1S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_1S_2	GEN_ARGS_SLEN_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_1S_4	GEN_ARGS_SLEN_1S_4(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_2S_1	GEN_ARGS_SLEN_2S_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_2S_3	GEN_ARGS_SLEN_2S_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_3S_2	GEN_ARGS_SLEN_3S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_3S_1	GEN_ARGS_SLEN_3S_1(DECLARE_KERN_ARGS)

///////////////////

#define DECLARE_KERN_ARGS_FAST_DBM_2SRCS	GEN_ARGS_FAST_DBM_2SRCS(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_DBM_1S_		GEN_ARGS_FAST_DBM_1S_(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_DBM_1S_1SRC	GEN_ARGS_FAST_DBM_1S_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_DBM_1SRC		GEN_ARGS_FAST_DBM_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_DBM_SBM		GEN_ARGS_FAST_DBM_SBM(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_EQSP_DBM_2SRCS	GEN_ARGS_EQSP_DBM_2SRCS(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_DBM_1S_		GEN_ARGS_EQSP_DBM_1S_(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_DBM_1S_1SRC	GEN_ARGS_EQSP_DBM_1S_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_DBM_1SRC		GEN_ARGS_EQSP_DBM_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_DBM_SBM		GEN_ARGS_EQSP_DBM_SBM(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_SLOW_DBM_2SRCS	GEN_ARGS_SLOW_DBM_2SRCS(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_DBM_1S_		GEN_ARGS_SLOW_DBM_1S_(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_DBM_1S_1SRC	GEN_ARGS_SLOW_DBM_1S_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_DBM_1SRC		GEN_ARGS_SLOW_DBM_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_DBM_SBM		GEN_ARGS_SLOW_DBM_SBM(DECLARE_KERN_ARGS)


#define DECLARE_KERN_ARGS_FLEN_DBM_2SRCS	GEN_ARGS_FLEN_DBM_2SRCS(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_DBM_1S_		GEN_ARGS_FLEN_DBM_1S_(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_DBM_1S_1SRC	GEN_ARGS_FLEN_DBM_1S_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_DBM_1SRC	GEN_ARGS_FLEN_DBM_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_DBM_SBM		GEN_ARGS_FLEN_DBM_SBM(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_ELEN_DBM_2SRCS	GEN_ARGS_ELEN_DBM_2SRCS(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_DBM_1S_		GEN_ARGS_ELEN_DBM_1S_(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_DBM_1S_1SRC	GEN_ARGS_ELEN_DBM_1S_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_DBM_1SRC	GEN_ARGS_ELEN_DBM_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_DBM_SBM		GEN_ARGS_ELEN_DBM_SBM(DECLARE_KERN_ARGS)

#define DECLARE_KERN_ARGS_SLEN_DBM_2SRCS	GEN_ARGS_SLEN_DBM_2SRCS(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_DBM_1S_		GEN_ARGS_SLEN_DBM_1S_(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_DBM_1S_1SRC	GEN_ARGS_SLEN_DBM_1S_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_DBM_1SRC		GEN_ARGS_SLEN_DBM_1SRC(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_DBM_SBM		GEN_ARGS_SLEN_DBM_SBM(DECLARE_KERN_ARGS)

/////////////////////

// real, source bitmap

#define DECLARE_KERN_ARGS_FAST_SBM_1		GEN_ARGS_FAST_SBM_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_SBM_3		GEN_ARGS_FAST_SBM_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_SBM_1S_2		GEN_ARGS_FAST_SBM_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_SBM_2S_1		GEN_ARGS_FAST_SBM_2S_1(DECLARE_KERN_ARGS)

// complex, source bitmap

#define DECLARE_KERN_ARGS_FAST_SBM_CPX_3	GEN_ARGS_FAST_SBM_CPX_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_SBM_CPX_1S_2	GEN_ARGS_FAST_SBM_CPX_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_SBM_CPX_2S_1	GEN_ARGS_FAST_SBM_CPX_2S_1(DECLARE_KERN_ARGS)

// quaternion, source bitmap

#define DECLARE_KERN_ARGS_FAST_SBM_QUAT_3	GEN_ARGS_FAST_SBM_QUAT_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_SBM_QUAT_1S_2	GEN_ARGS_FAST_SBM_QUAT_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FAST_SBM_QUAT_2S_1	GEN_ARGS_FAST_SBM_QUAT_2S_1(DECLARE_KERN_ARGS)

/////////////////////

// real, source bitmap

#define DECLARE_KERN_ARGS_EQSP_SBM_1		GEN_ARGS_EQSP_SBM_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_SBM_3		GEN_ARGS_EQSP_SBM_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_SBM_1S_2		GEN_ARGS_EQSP_SBM_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_SBM_2S_1		GEN_ARGS_EQSP_SBM_2S_1(DECLARE_KERN_ARGS)

// complex, source bitmap

#define DECLARE_KERN_ARGS_EQSP_SBM_CPX_3	GEN_ARGS_EQSP_SBM_CPX_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_SBM_CPX_1S_2	GEN_ARGS_EQSP_SBM_CPX_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_SBM_CPX_2S_1	GEN_ARGS_EQSP_SBM_CPX_2S_1(DECLARE_KERN_ARGS)

// quaternion, source bitmap

#define DECLARE_KERN_ARGS_EQSP_SBM_QUAT_3	GEN_ARGS_EQSP_SBM_QUAT_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_SBM_QUAT_1S_2	GEN_ARGS_EQSP_SBM_QUAT_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_EQSP_SBM_QUAT_2S_1	GEN_ARGS_EQSP_SBM_QUAT_2S_1(DECLARE_KERN_ARGS)

/////////////////////

// real, source bitmap

#define DECLARE_KERN_ARGS_SLOW_SBM_1		GEN_ARGS_SLOW_SBM_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_SBM_3		GEN_ARGS_SLOW_SBM_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_SBM_1S_2		GEN_ARGS_SLOW_SBM_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_SBM_2S_1		GEN_ARGS_SLOW_SBM_2S_1(DECLARE_KERN_ARGS)

// complex, source bitmap

#define DECLARE_KERN_ARGS_SLOW_SBM_CPX_3	GEN_ARGS_SLOW_SBM_CPX_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_SBM_CPX_1S_2	GEN_ARGS_SLOW_SBM_CPX_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_SBM_CPX_2S_1	GEN_ARGS_SLOW_SBM_CPX_2S_1(DECLARE_KERN_ARGS)

// quaternion, source bitmap

#define DECLARE_KERN_ARGS_SLOW_SBM_QUAT_3	GEN_ARGS_SLOW_SBM_QUAT_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_SBM_QUAT_1S_2	GEN_ARGS_SLOW_SBM_QUAT_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLOW_SBM_QUAT_2S_1	GEN_ARGS_SLOW_SBM_QUAT_2S_1(DECLARE_KERN_ARGS)


/////////////////////

// real, source bitmap

#define DECLARE_KERN_ARGS_FLEN_SBM_1		GEN_ARGS_FLEN_SBM_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_SBM_3		GEN_ARGS_FLEN_SBM_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_SBM_1S_2		GEN_ARGS_FLEN_SBM_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_SBM_2S_1		GEN_ARGS_FLEN_SBM_2S_1(DECLARE_KERN_ARGS)

// complex, source bitmap

#define DECLARE_KERN_ARGS_FLEN_SBM_CPX_3	GEN_ARGS_FLEN_SBM_CPX_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_SBM_CPX_1S_2	GEN_ARGS_FLEN_SBM_CPX_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_SBM_CPX_2S_1	GEN_ARGS_FLEN_SBM_CPX_2S_1(DECLARE_KERN_ARGS)

// quaternion, source bitmap

#define DECLARE_KERN_ARGS_FLEN_SBM_QUAT_3	GEN_ARGS_FLEN_SBM_QUAT_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_SBM_QUAT_1S_2	GEN_ARGS_FLEN_SBM_QUAT_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_FLEN_SBM_QUAT_2S_1	GEN_ARGS_FLEN_SBM_QUAT_2S_1(DECLARE_KERN_ARGS)

/////////////////////

// real, source bitmap

#define DECLARE_KERN_ARGS_ELEN_SBM_1		GEN_ARGS_ELEN_SBM_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_SBM_3		GEN_ARGS_ELEN_SBM_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_SBM_1S_2		GEN_ARGS_ELEN_SBM_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_SBM_2S_1		GEN_ARGS_ELEN_SBM_2S_1(DECLARE_KERN_ARGS)

// complex, source bitmap

#define DECLARE_KERN_ARGS_ELEN_SBM_CPX_3	GEN_ARGS_ELEN_SBM_CPX_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_SBM_CPX_1S_2	GEN_ARGS_ELEN_SBM_CPX_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_SBM_CPX_2S_1	GEN_ARGS_ELEN_SBM_CPX_2S_1(DECLARE_KERN_ARGS)

// quaternion, source bitmap

#define DECLARE_KERN_ARGS_ELEN_SBM_QUAT_3	GEN_ARGS_ELEN_SBM_QUAT_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_SBM_QUAT_1S_2	GEN_ARGS_ELEN_SBM_QUAT_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_ELEN_SBM_QUAT_2S_1	GEN_ARGS_ELEN_SBM_QUAT_2S_1(DECLARE_KERN_ARGS)

/////////////////////

// real, source bitmap

#define DECLARE_KERN_ARGS_SLEN_SBM_1		GEN_ARGS_SLEN_SBM_1(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_SBM_3		GEN_ARGS_SLEN_SBM_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_SBM_1S_2		GEN_ARGS_SLEN_SBM_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_SBM_2S_1		GEN_ARGS_SLEN_SBM_2S_1(DECLARE_KERN_ARGS)

// complex, source bitmap

#define DECLARE_KERN_ARGS_SLEN_SBM_CPX_3	GEN_ARGS_SLEN_SBM_CPX_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_SBM_CPX_1S_2	GEN_ARGS_SLEN_SBM_CPX_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_SBM_CPX_2S_1	GEN_ARGS_SLEN_SBM_CPX_2S_1(DECLARE_KERN_ARGS)

// quaternion, source bitmap

#define DECLARE_KERN_ARGS_SLEN_SBM_QUAT_3	GEN_ARGS_SLEN_SBM_QUAT_3(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_SBM_QUAT_1S_2	GEN_ARGS_SLEN_SBM_QUAT_1S_2(DECLARE_KERN_ARGS)
#define DECLARE_KERN_ARGS_SLEN_SBM_QUAT_2S_1	GEN_ARGS_SLEN_SBM_QUAT_2S_1(DECLARE_KERN_ARGS)


/******************* KERN_ARGS ***************************/

///////////////////
// Building blocks

#define KERN_ARGS_1S		VA_SCALAR_VAL_STD(vap,0)
#define KERN_ARGS_2S		KERN_ARGS_1S, VA_SCALAR_VAL_STD(vap,1)
#define KERN_ARGS_3S		KERN_ARGS_2S, VA_SCALAR_VAL_STD(vap,2)

#define KERN_ARGS_CPX_1S	VA_SCALAR_VAL_STDCPX(vap,0)
#define KERN_ARGS_CPX_2S	KERN_ARGS_CPX_1S , VA_SCALAR_VAL_STDCPX(vap,1)

#define KERN_ARGS_QUAT_1S	VA_SCALAR_VAL_STDQUAT(vap,0)
#define KERN_ARGS_QUAT_2S	KERN_ARGS_QUAT_1S , VA_SCALAR_VAL_STDQUAT(vap,1)

#define KERN_ARGS_SLOW_SIZE		VA_SLOW_SIZE(vap)

#define KERN_ARGS_FAST_CONV_DEST(t)	(t *) VA_DEST_PTR(vap)
#define KERN_ARGS_FAST_1		(dest_type *) VA_DEST_PTR(vap)
#define KERN_ARGS_FAST_SRC1	(std_type *) VA_SRC1_PTR(vap)
#define KERN_ARGS_FAST_SRC2	(std_type *) VA_SRC2_PTR(vap)
#define KERN_ARGS_FAST_SRC3	(std_type *) VA_SRC3_PTR(vap)
#define KERN_ARGS_FAST_SRC4	(std_type *) VA_SRC4_PTR(vap)

// complex stuff

#define KERN_ARGS_FAST_CPX_1	(dest_cpx *) VA_DEST_PTR(vap)
#define KERN_ARGS_FAST_CPX_SRC1	(std_cpx *) VA_SRC1_PTR(vap)
#define KERN_ARGS_FAST_CPX_SRC2	(std_cpx *) VA_SRC2_PTR(vap)
#define KERN_ARGS_FAST_CPX_SRC3	(std_cpx *) VA_SRC3_PTR(vap)
#define KERN_ARGS_FAST_CPX_SRC4	(std_cpx *) VA_SRC4_PTR(vap)

// quaternion stuff

#define KERN_ARGS_FAST_QUAT_1		(dest_quat *) VA_DEST_PTR(vap)
#define KERN_ARGS_FAST_QUAT_SRC1		(std_quat *) VA_SRC1_PTR(vap)
#define KERN_ARGS_FAST_QUAT_SRC2		(std_quat *) VA_SRC2_PTR(vap)
#define KERN_ARGS_FAST_QUAT_SRC3		(std_quat *) VA_SRC3_PTR(vap)
#define KERN_ARGS_FAST_QUAT_SRC4		(std_quat *) VA_SRC4_PTR(vap)

// EQSP real

#define KERN_ARGS_EQSP_INC1	VA_DEST_INC(vap)
#define KERN_ARGS_EQSP_INC2	VA_SRC1_INC(vap)
#define KERN_ARGS_EQSP_INC3	VA_SRC2_INC(vap)
#define KERN_ARGS_EQSP_INC4	VA_SRC3_INC(vap)
#define KERN_ARGS_EQSP_INC5	VA_SRC4_INC(vap)

#define KERN_ARGS_DBM_INC	VA_DBM_INC(vap)

// complex, eqsp

// real, slow

// these are DIM3's, not the object increment sets...

#define KERN_ARGS_SLOW_INC1	dst_vwxyz_incr
#define KERN_ARGS_SLOW_INC2	s1_vwxyz_incr
#define KERN_ARGS_SLOW_INC3	s2_vwxyz_incr
#define KERN_ARGS_SLOW_INC4	s3_vwxyz_incr
#define KERN_ARGS_SLOW_INC5	s4_vwxyz_incr

#define KERN_ARGS_FAST_LEN	VA_LENGTH(vap)
#define KERN_ARGS_EQSP_LEN	VA_LENGTH(vap)
//#define KERN_ARGS_SLOW_LEN	VA_XYZ_LEN(vap)			// a local variable!?
#define KERN_ARGS_SLOW_LEN	VA_ITERATION_TOTAL(vap)			// a local variable!?

#define KERN_ARGS_FAST_SBM	(bitmap_word *) VA_SBM_PTR(vap) , VA_SBM_BIT0(vap)
#define KERN_ARGS_EQSP_SBM	KERN_ARGS_FAST_SBM, VA_SBM_INC(vap)
//#define KERN_ARGS_SLOW_SBM	KERN_ARGS_FAST_SBM, sbm_xyz_incr
#define KERN_ARGS_SLOW_SBM	KERN_ARGS_FAST_SBM, sbm_vwxyz_incr

//#define KERN_ARGS_FAST_DBM	(bitmap_word *) VA_DBM_PTR(vap) , VA_DBM_BIT0(vap)
#define KERN_ARGS_FAST_DBM	(bitmap_word *) VA_DBM_PTR(vap)

//#define KERN_ARGS_EQSP_DBM	KERN_ARGS_FAST_DBM , VA_DBM_INC(vap)
//#define KERN_ARGS_EQSP_DBM	KERN_ARGS_FAST_DBM , KERN_ARGS_DBM_INC
#define KERN_ARGS_EQSP_DBM	KERN_ARGS_FAST_DBM

//#define KERN_ARGS_SLOW_DBM	KERN_ARGS_FAST_DBM , dbm_xyz_incr
//#define KERN_ARGS_SLOW_DBM	KERN_ARGS_FAST_DBM , dbm_vwxyz_incr

#define KERN_ARGS_SLOW_DBM	KERN_ARGS_FAST_DBM


// Compound arg lists
/****************************************/

#define KERN_ARGS_FAST_CONV(type)	GEN_ARGS_FAST_CONV(KERN_ARGS,type)
#define KERN_ARGS_FAST_2		GEN_ARGS_FAST_2(KERN_ARGS)
#define KERN_ARGS_FAST_2		GEN_ARGS_FAST_2(KERN_ARGS)
#define KERN_ARGS_FAST_3		GEN_ARGS_FAST_3(KERN_ARGS)
#define KERN_ARGS_FAST_4		GEN_ARGS_FAST_4(KERN_ARGS)
#define KERN_ARGS_FAST_5		GEN_ARGS_FAST_5(KERN_ARGS)
#define KERN_ARGS_FAST_1SRC		GEN_ARGS_FAST_1SRC(KERN_ARGS)
#define KERN_ARGS_FAST_2SRCS		GEN_ARGS_FAST_2SRCS(KERN_ARGS)

#define KERN_ARGS_FAST_CPX_2		GEN_ARGS_FAST_CPX_2(KERN_ARGS)
#define KERN_ARGS_FAST_RC_2		GEN_ARGS_FAST_RC_2(KERN_ARGS)

#define KERN_ARGS_FAST_CPX_3		GEN_ARGS_FAST_CPX_3(KERN_ARGS)
#define KERN_ARGS_FAST_CPX_4		GEN_ARGS_FAST_CPX_4(KERN_ARGS)
#define KERN_ARGS_FAST_CPX_5		GEN_ARGS_FAST_CPX_5(KERN_ARGS)
#define KERN_ARGS_FAST_CCR_3		GEN_ARGS_FAST_CCR_3(KERN_ARGS)

#define KERN_ARGS_FAST_CR_1S_2		GEN_ARGS_FAST_CR_1S_2(KERN_ARGS)
#define KERN_ARGS_FAST_CPX_1S_2		GEN_ARGS_FAST_CPX_1S_2(KERN_ARGS)
#define KERN_ARGS_FAST_CPX_1S_1		GEN_ARGS_FAST_CPX_1S_1(KERN_ARGS)
#define KERN_ARGS_FAST_CPX_2S_1		GEN_ARGS_FAST_CPX_2S_1(KERN_ARGS)

#define KERN_ARGS_FAST_QUAT_2		GEN_ARGS_FAST_QUAT_2(KERN_ARGS)
#define KERN_ARGS_FAST_QUAT_3		GEN_ARGS_FAST_QUAT_3(KERN_ARGS)
#define KERN_ARGS_FAST_QUAT_4		GEN_ARGS_FAST_QUAT_4(KERN_ARGS)
#define KERN_ARGS_FAST_QUAT_5		GEN_ARGS_FAST_QUAT_5(KERN_ARGS)
#define KERN_ARGS_FAST_QQR_3		GEN_ARGS_FAST_QQR_3(KERN_ARGS)

#define KERN_ARGS_FAST_QR_1S_2		GEN_ARGS_FAST_QR_1S_2(KERN_ARGS)
#define KERN_ARGS_FAST_QUAT_1S_2	GEN_ARGS_FAST_QUAT_1S_2(KERN_ARGS)
#define KERN_ARGS_FAST_QUAT_1S_1	GEN_ARGS_FAST_QUAT_1S_1(KERN_ARGS)
#define KERN_ARGS_FAST_QUAT_2S_1	GEN_ARGS_FAST_QUAT_2S_1(KERN_ARGS)

/////////////////////////////

#define KERN_ARGS_EQSP_1SRC		GEN_ARGS_EQSP_1SRC(KERN_ARGS)
#define KERN_ARGS_EQSP_2SRCS		GEN_ARGS_EQSP_2SRCS(KERN_ARGS)
#define KERN_ARGS_EQSP_CONV(type)	GEN_ARGS_EQSP_CONV(KERN_ARGS,type)
#define KERN_ARGS_EQSP_2		GEN_ARGS_EQSP_2(KERN_ARGS)
#define KERN_ARGS_EQSP_3		GEN_ARGS_EQSP_3(KERN_ARGS)
#define KERN_ARGS_EQSP_4		GEN_ARGS_EQSP_4(KERN_ARGS)
#define KERN_ARGS_EQSP_5		GEN_ARGS_EQSP_5(KERN_ARGS)

#define KERN_ARGS_EQSP_CPX_1SRC		GEN_ARGS_EQSP_CPX_1SRC(KERN_ARGS)
#define KERN_ARGS_EQSP_CPX_2SRCS	GEN_ARGS_EQSP_CPX_2SRCS(KERN_ARGS)
#define KERN_ARGS_EQSP_CPX_2		GEN_ARGS_EQSP_CPX_2(KERN_ARGS)
#define KERN_ARGS_EQSP_CPX_3		GEN_ARGS_EQSP_CPX_3(KERN_ARGS)
#define KERN_ARGS_EQSP_CPX_4		GEN_ARGS_EQSP_CPX_4(KERN_ARGS)
#define KERN_ARGS_EQSP_CPX_5		GEN_ARGS_EQSP_CPX_5(KERN_ARGS)

#define KERN_ARGS_EQSP_CCR_3		GEN_ARGS_EQSP_CCR_3(KERN_ARGS)
#define KERN_ARGS_EQSP_RC_2		GEN_ARGS_EQSP_RC_2(KERN_ARGS)
#define KERN_ARGS_EQSP_CR_1S_2		GEN_ARGS_EQSP_CR_1S_2(KERN_ARGS)
#define KERN_ARGS_EQSP_CPX_1S_2		GEN_ARGS_EQSP_CPX_1S_2(KERN_ARGS)
#define KERN_ARGS_EQSP_CPX_1S_1		GEN_ARGS_EQSP_CPX_1S_1(KERN_ARGS)
#define KERN_ARGS_EQSP_CPX_2S_1		GEN_ARGS_EQSP_CPX_2S_1(KERN_ARGS)

// quaternion, eqsp

#define KERN_ARGS_EQSP_QUAT_1SRC	GEN_ARGS_EQSP_QUAT_1SRC(KERN_ARGS)
#define KERN_ARGS_EQSP_QUAT_2SRCS	GEN_ARGS_EQSP_QUAT_2SRCS(KERN_ARGS)
#define KERN_ARGS_EQSP_QUAT_2		GEN_ARGS_EQSP_QUAT_2(KERN_ARGS)
#define KERN_ARGS_EQSP_QUAT_3		GEN_ARGS_EQSP_QUAT_3(KERN_ARGS)
#define KERN_ARGS_EQSP_QUAT_4		GEN_ARGS_EQSP_QUAT_4(KERN_ARGS)
#define KERN_ARGS_EQSP_QUAT_5		GEN_ARGS_EQSP_QUAT_5(KERN_ARGS)

#define KERN_ARGS_EQSP_QQR_3		GEN_ARGS_EQSP_QQR_3(KERN_ARGS)
#define KERN_ARGS_EQSP_RQ_2		GEN_ARGS_EQSP_RQ_2(KERN_ARGS)
#define KERN_ARGS_EQSP_QR_1S_2		GEN_ARGS_EQSP_QR_1S_2(KERN_ARGS)
#define KERN_ARGS_EQSP_QUAT_1S_2	GEN_ARGS_EQSP_QUAT_1S_2(KERN_ARGS)
#define KERN_ARGS_EQSP_QUAT_1S_1	GEN_ARGS_EQSP_QUAT_1S_1(KERN_ARGS)
#define KERN_ARGS_EQSP_QUAT_2S_1	GEN_ARGS_EQSP_QUAT_2S_1(KERN_ARGS)

////////////////////////////////////////

#define KERN_ARGS_SLOW_CONV(type)	GEN_ARGS_SLOW_CONV(KERN_ARGS,type)
#define KERN_ARGS_SLOW_2		GEN_ARGS_SLOW_2(KERN_ARGS)
#define KERN_ARGS_SLOW_3		GEN_ARGS_SLOW_3(KERN_ARGS)
#define KERN_ARGS_SLOW_4		GEN_ARGS_SLOW_4(KERN_ARGS)
#define KERN_ARGS_SLOW_5		GEN_ARGS_SLOW_5(KERN_ARGS)

#define KERN_ARGS_SLOW_CPX_2		GEN_ARGS_SLOW_CPX_2(KERN_ARGS)
#define KERN_ARGS_SLOW_CPX_3		GEN_ARGS_SLOW_CPX_3(KERN_ARGS)
#define KERN_ARGS_SLOW_CPX_4		GEN_ARGS_SLOW_CPX_4(KERN_ARGS)
#define KERN_ARGS_SLOW_CPX_5		GEN_ARGS_SLOW_CPX_5(KERN_ARGS)


#define KERN_ARGS_SLOW_CCR_3		GEN_ARGS_SLOW_CCR_3(KERN_ARGS)
#define KERN_ARGS_SLOW_RC_2		GEN_ARGS_SLOW_RC_2(KERN_ARGS)
#define KERN_ARGS_SLOW_CR_1S_2		GEN_ARGS_SLOW_CR_1S_2(KERN_ARGS)
#define KERN_ARGS_SLOW_CPX_1S_2		GEN_ARGS_SLOW_CPX_1S_2(KERN_ARGS)
#define KERN_ARGS_SLOW_CPX_1S_1		GEN_ARGS_SLOW_CPX_1S_1(KERN_ARGS)
#define KERN_ARGS_SLOW_CPX_2S_1		GEN_ARGS_SLOW_CPX_2S_1(KERN_ARGS)

#define KERN_ARGS_SLOW_QUAT_2		GEN_ARGS_SLOW_QUAT_2(KERN_ARGS)
#define KERN_ARGS_SLOW_QUAT_3		GEN_ARGS_SLOW_QUAT_3(KERN_ARGS)
#define KERN_ARGS_SLOW_QUAT_4		GEN_ARGS_SLOW_QUAT_4(KERN_ARGS)
#define KERN_ARGS_SLOW_QUAT_5		GEN_ARGS_SLOW_QUAT_5(KERN_ARGS)


#define KERN_ARGS_SLOW_QQR_3		GEN_ARGS_SLOW_QQR_3(KERN_ARGS)
#define KERN_ARGS_SLOW_RQ_2		GEN_ARGS_SLOW_RQ_2(KERN_ARGS)
#define KERN_ARGS_SLOW_QR_1S_2		GEN_ARGS_SLOW_QR_1S_2(KERN_ARGS)
#define KERN_ARGS_SLOW_QUAT_1S_2	GEN_ARGS_SLOW_QUAT_1S_2(KERN_ARGS)
#define KERN_ARGS_SLOW_QUAT_1S_1	GEN_ARGS_SLOW_QUAT_1S_1(KERN_ARGS)
#define KERN_ARGS_SLOW_QUAT_2S_1	GEN_ARGS_SLOW_QUAT_2S_1(KERN_ARGS)

////////////////

#define KERN_ARGS_SLOW_1SRC	GEN_ARGS_SLOW_1SRC(KERN_ARGS)
#define KERN_ARGS_SLOW_2SRCS	GEN_ARGS_SLOW_2SRCS(KERN_ARGS)

#define KERN_ARGS_FLEN_CONV(t)	GEN_ARGS_FLEN_CONV(KERN_ARGS,t)
#define KERN_ARGS_FLEN_1	GEN_ARGS_FLEN_1(KERN_ARGS)
#define KERN_ARGS_FLEN_2	GEN_ARGS_FLEN_2(KERN_ARGS)
#define KERN_ARGS_FLEN_3	GEN_ARGS_FLEN_3(KERN_ARGS)
#define KERN_ARGS_FLEN_4	GEN_ARGS_FLEN_4(KERN_ARGS)
#define KERN_ARGS_FLEN_5	GEN_ARGS_FLEN_5(KERN_ARGS)

#define KERN_ARGS_ELEN_CONV(t)	GEN_ARGS_ELEN_CONV(KERN_ARGS,t)
#define KERN_ARGS_ELEN_1	GEN_ARGS_ELEN_1(KERN_ARGS)
#define KERN_ARGS_ELEN_2	GEN_ARGS_ELEN_2(KERN_ARGS)
#define KERN_ARGS_ELEN_3	GEN_ARGS_ELEN_3(KERN_ARGS)
#define KERN_ARGS_ELEN_4	GEN_ARGS_ELEN_4(KERN_ARGS)
#define KERN_ARGS_ELEN_5	GEN_ARGS_ELEN_5(KERN_ARGS)

#define KERN_ARGS_SLEN_CONV(t)	GEN_ARGS_SLEN_CONV(KERN_ARGS,t)
#define KERN_ARGS_SLEN_1	GEN_ARGS_SLEN_1(KERN_ARGS)
#define KERN_ARGS_SLEN_2	GEN_ARGS_SLEN_2(KERN_ARGS)
#define KERN_ARGS_SLEN_3	GEN_ARGS_SLEN_3(KERN_ARGS)
#define KERN_ARGS_SLEN_4	GEN_ARGS_SLEN_4(KERN_ARGS)
#define KERN_ARGS_SLEN_5	GEN_ARGS_SLEN_5(KERN_ARGS)

// complex, with len

#define KERN_ARGS_FLEN_CPX_1	GEN_ARGS_FLEN_CPX_1(KERN_ARGS)
#define KERN_ARGS_FLEN_CPX_2	GEN_ARGS_FLEN_CPX_2(KERN_ARGS)
#define KERN_ARGS_FLEN_CPX_3	GEN_ARGS_FLEN_CPX_3(KERN_ARGS)
#define KERN_ARGS_FLEN_CPX_4	GEN_ARGS_FLEN_CPX_4(KERN_ARGS)
#define KERN_ARGS_FLEN_CPX_5	GEN_ARGS_FLEN_CPX_5(KERN_ARGS)

#define KERN_ARGS_ELEN_CPX_1	GEN_ARGS_ELEN_CPX_1(KERN_ARGS)
#define KERN_ARGS_ELEN_CPX_2	GEN_ARGS_ELEN_CPX_2(KERN_ARGS)
#define KERN_ARGS_ELEN_CPX_3	GEN_ARGS_ELEN_CPX_3(KERN_ARGS)
#define KERN_ARGS_ELEN_CPX_4	GEN_ARGS_ELEN_CPX_4(KERN_ARGS)
#define KERN_ARGS_ELEN_CPX_5	GEN_ARGS_ELEN_CPX_5(KERN_ARGS)

#define KERN_ARGS_SLEN_CPX_1	GEN_ARGS_SLEN_CPX_1(KERN_ARGS)
#define KERN_ARGS_SLEN_CPX_2	GEN_ARGS_SLEN_CPX_2(KERN_ARGS)
#define KERN_ARGS_SLEN_CPX_3	GEN_ARGS_SLEN_CPX_3(KERN_ARGS)
#define KERN_ARGS_SLEN_CPX_4	GEN_ARGS_SLEN_CPX_4(KERN_ARGS)
#define KERN_ARGS_SLEN_CPX_5	GEN_ARGS_SLEN_CPX_5(KERN_ARGS)

#define KERN_ARGS_FLEN_RC_2	GEN_ARGS_FLEN_RC_2(KERN_ARGS)
#define KERN_ARGS_ELEN_RC_2	GEN_ARGS_ELEN_RC_2(KERN_ARGS)
#define KERN_ARGS_SLEN_RC_2	GEN_ARGS_SLEN_RC_2(KERN_ARGS)

#define KERN_ARGS_FLEN_CCR_3	GEN_ARGS_FLEN_CCR_3(KERN_ARGS)
#define KERN_ARGS_ELEN_CCR_3	GEN_ARGS_ELEN_CCR_3(KERN_ARGS)
#define KERN_ARGS_SLEN_CCR_3	GEN_ARGS_SLEN_CCR_3(KERN_ARGS)

#define KERN_ARGS_FLEN_CR_1S_2	GEN_ARGS_FLEN_CR_1S_2(KERN_ARGS)
#define KERN_ARGS_ELEN_CR_1S_2	GEN_ARGS_ELEN_CR_1S_2(KERN_ARGS)
#define KERN_ARGS_SLEN_CR_1S_2	GEN_ARGS_SLEN_CR_1S_2(KERN_ARGS)

#define KERN_ARGS_FLEN_CPX_1S_2	GEN_ARGS_FLEN_CPX_1S_2(KERN_ARGS)
#define KERN_ARGS_ELEN_CPX_1S_2	GEN_ARGS_ELEN_CPX_1S_2(KERN_ARGS)
#define KERN_ARGS_SLEN_CPX_1S_2	GEN_ARGS_SLEN_CPX_1S_2(KERN_ARGS)

#define KERN_ARGS_FLEN_CPX_1S_1	GEN_ARGS_FLEN_CPX_1S_1(KERN_ARGS)
#define KERN_ARGS_ELEN_CPX_1S_1	GEN_ARGS_ELEN_CPX_1S_1(KERN_ARGS)
#define KERN_ARGS_SLEN_CPX_1S_1	GEN_ARGS_SLEN_CPX_1S_1(KERN_ARGS)

#define KERN_ARGS_FLEN_CPX_2S_1	GEN_ARGS_FLEN_CPX_2S_1(KERN_ARGS)
#define KERN_ARGS_ELEN_CPX_2S_1	GEN_ARGS_ELEN_CPX_2S_1(KERN_ARGS)
#define KERN_ARGS_SLEN_CPX_2S_1	GEN_ARGS_SLEN_CPX_2S_1(KERN_ARGS)

// quaternion, with len

#define KERN_ARGS_FLEN_QUAT_1	GEN_ARGS_FLEN_QUAT_1(KERN_ARGS)
#define KERN_ARGS_FLEN_QUAT_2	GEN_ARGS_FLEN_QUAT_2(KERN_ARGS)
#define KERN_ARGS_FLEN_QUAT_3	GEN_ARGS_FLEN_QUAT_3(KERN_ARGS)
#define KERN_ARGS_FLEN_QUAT_4	GEN_ARGS_FLEN_QUAT_4(KERN_ARGS)
#define KERN_ARGS_FLEN_QUAT_5	GEN_ARGS_FLEN_QUAT_5(KERN_ARGS)

#define KERN_ARGS_ELEN_QUAT_1	GEN_ARGS_ELEN_QUAT_1(KERN_ARGS)
#define KERN_ARGS_ELEN_QUAT_2	GEN_ARGS_ELEN_QUAT_2(KERN_ARGS)
#define KERN_ARGS_ELEN_QUAT_3	GEN_ARGS_ELEN_QUAT_3(KERN_ARGS)
#define KERN_ARGS_ELEN_QUAT_4	GEN_ARGS_ELEN_QUAT_4(KERN_ARGS)
#define KERN_ARGS_ELEN_QUAT_5	GEN_ARGS_ELEN_QUAT_5(KERN_ARGS)

#define KERN_ARGS_SLEN_QUAT_1	GEN_ARGS_SLEN_QUAT_1(KERN_ARGS)
#define KERN_ARGS_SLEN_QUAT_2	GEN_ARGS_SLEN_QUAT_2(KERN_ARGS)
#define KERN_ARGS_SLEN_QUAT_3	GEN_ARGS_SLEN_QUAT_3(KERN_ARGS)
#define KERN_ARGS_SLEN_QUAT_4	GEN_ARGS_SLEN_QUAT_4(KERN_ARGS)
#define KERN_ARGS_SLEN_QUAT_5	GEN_ARGS_SLEN_QUAT_5(KERN_ARGS)

#define KERN_ARGS_FLEN_RQ_2		GEN_ARGS_FLEN_RQ_2(KERN_ARGS)
#define KERN_ARGS_FLEN_QQR_3		GEN_ARGS_FLEN_QQR_3(KERN_ARGS)
#define KERN_ARGS_FLEN_QR_1S_2		GEN_ARGS_FLEN_QR_1S_2(KERN_ARGS)
#define KERN_ARGS_FLEN_QUAT_1S_2	GEN_ARGS_FLEN_QUAT_1S_2(KERN_ARGS)
#define KERN_ARGS_FLEN_QUAT_1S_1	GEN_ARGS_FLEN_QUAT_1S_1(KERN_ARGS)
#define KERN_ARGS_FLEN_QUAT_2S_1	GEN_ARGS_FLEN_QUAT_2S_1(KERN_ARGS)

#define KERN_ARGS_ELEN_RQ_2		GEN_ARGS_ELEN_RQ_2(KERN_ARGS)
#define KERN_ARGS_ELEN_QQR_3		GEN_ARGS_ELEN_QQR_3(KERN_ARGS)
#define KERN_ARGS_ELEN_QR_1S_2		GEN_ARGS_ELEN_QR_1S_2(KERN_ARGS)
#define KERN_ARGS_ELEN_QUAT_1S_2	GEN_ARGS_ELEN_QUAT_1S_2(KERN_ARGS)
#define KERN_ARGS_ELEN_QUAT_1S_1	GEN_ARGS_ELEN_QUAT_1S_1(KERN_ARGS)
#define KERN_ARGS_ELEN_QUAT_2S_1	GEN_ARGS_ELEN_QUAT_2S_1(KERN_ARGS)

#define KERN_ARGS_SLEN_RQ_2		GEN_ARGS_SLEN_RQ_2(KERN_ARGS)
#define KERN_ARGS_SLEN_QQR_3		GEN_ARGS_SLEN_QQR_3(KERN_ARGS)
#define KERN_ARGS_SLEN_QR_1S_2		GEN_ARGS_SLEN_QR_1S_2(KERN_ARGS)
#define KERN_ARGS_SLEN_QUAT_1S_2	GEN_ARGS_SLEN_QUAT_1S_2(KERN_ARGS)
#define KERN_ARGS_SLEN_QUAT_1S_1	GEN_ARGS_SLEN_QUAT_1S_1(KERN_ARGS)
#define KERN_ARGS_SLEN_QUAT_2S_1	GEN_ARGS_SLEN_QUAT_2S_1(KERN_ARGS)

//////////////////////////

#define KERN_ARGS_FAST_1S_1	GEN_ARGS_FAST_1S_1(KERN_ARGS)
#define KERN_ARGS_FAST_1S_2	GEN_ARGS_FAST_1S_2(KERN_ARGS)
#define KERN_ARGS_FAST_1S_4	GEN_ARGS_FAST_1S_4(KERN_ARGS)
#define KERN_ARGS_FAST_2S_1	GEN_ARGS_FAST_2S_1(KERN_ARGS)
#define KERN_ARGS_FAST_2S_3	GEN_ARGS_FAST_2S_3(KERN_ARGS)
#define KERN_ARGS_FAST_3S_2	GEN_ARGS_FAST_3S_2(KERN_ARGS)
#define KERN_ARGS_FAST_3S_1	GEN_ARGS_FAST_3S_1(KERN_ARGS)

#define KERN_ARGS_EQSP_1S_1	GEN_ARGS_EQSP_1S_1(KERN_ARGS)
#define KERN_ARGS_EQSP_1S_2	GEN_ARGS_EQSP_1S_2(KERN_ARGS)
#define KERN_ARGS_EQSP_1S_4	GEN_ARGS_EQSP_1S_4(KERN_ARGS)
#define KERN_ARGS_EQSP_2S_1	GEN_ARGS_EQSP_2S_1(KERN_ARGS)
#define KERN_ARGS_EQSP_2S_3	GEN_ARGS_EQSP_2S_3(KERN_ARGS)
#define KERN_ARGS_EQSP_3S_2	GEN_ARGS_EQSP_3S_2(KERN_ARGS)
#define KERN_ARGS_EQSP_3S_1	GEN_ARGS_EQSP_3S_1(KERN_ARGS)

#define KERN_ARGS_SLOW_1S_1	GEN_ARGS_SLOW_1S_1(KERN_ARGS)
#define KERN_ARGS_SLOW_1S_2	GEN_ARGS_SLOW_1S_2(KERN_ARGS)
#define KERN_ARGS_SLOW_1S_4	GEN_ARGS_SLOW_1S_4(KERN_ARGS)
#define KERN_ARGS_SLOW_2S_1	GEN_ARGS_SLOW_2S_1(KERN_ARGS)
#define KERN_ARGS_SLOW_2S_3	GEN_ARGS_SLOW_2S_3(KERN_ARGS)
#define KERN_ARGS_SLOW_3S_2	GEN_ARGS_SLOW_3S_2(KERN_ARGS)
#define KERN_ARGS_SLOW_3S_1	GEN_ARGS_SLOW_3S_1(KERN_ARGS)

#define KERN_ARGS_FLEN_1S_1	GEN_ARGS_FLEN_1S_1(KERN_ARGS)
#define KERN_ARGS_FLEN_1S_2	GEN_ARGS_FLEN_1S_2(KERN_ARGS)
#define KERN_ARGS_FLEN_1S_4	GEN_ARGS_FLEN_1S_4(KERN_ARGS)
#define KERN_ARGS_FLEN_2S_1	GEN_ARGS_FLEN_2S_1(KERN_ARGS)
#define KERN_ARGS_FLEN_2S_3	GEN_ARGS_FLEN_2S_3(KERN_ARGS)
#define KERN_ARGS_FLEN_3S_2	GEN_ARGS_FLEN_3S_2(KERN_ARGS)
#define KERN_ARGS_FLEN_3S_1	GEN_ARGS_FLEN_3S_1(KERN_ARGS)

#define KERN_ARGS_ELEN_1S_1	GEN_ARGS_ELEN_1S_1(KERN_ARGS)
#define KERN_ARGS_ELEN_1S_2	GEN_ARGS_ELEN_1S_2(KERN_ARGS)
#define KERN_ARGS_ELEN_1S_4	GEN_ARGS_ELEN_1S_4(KERN_ARGS)
#define KERN_ARGS_ELEN_2S_1	GEN_ARGS_ELEN_2S_1(KERN_ARGS)
#define KERN_ARGS_ELEN_2S_3	GEN_ARGS_ELEN_2S_3(KERN_ARGS)
#define KERN_ARGS_ELEN_3S_2	GEN_ARGS_ELEN_3S_2(KERN_ARGS)
#define KERN_ARGS_ELEN_3S_1	GEN_ARGS_ELEN_3S_1(KERN_ARGS)

#define KERN_ARGS_SLEN_1S_1	GEN_ARGS_SLEN_1S_1(KERN_ARGS)
#define KERN_ARGS_SLEN_1S_2	GEN_ARGS_SLEN_1S_2(KERN_ARGS)
#define KERN_ARGS_SLEN_1S_4	GEN_ARGS_SLEN_1S_4(KERN_ARGS)
#define KERN_ARGS_SLEN_2S_1	GEN_ARGS_SLEN_2S_1(KERN_ARGS)
#define KERN_ARGS_SLEN_2S_3	GEN_ARGS_SLEN_2S_3(KERN_ARGS)
#define KERN_ARGS_SLEN_3S_2	GEN_ARGS_SLEN_3S_2(KERN_ARGS)
#define KERN_ARGS_SLEN_3S_1	GEN_ARGS_SLEN_3S_1(KERN_ARGS)

#define KERN_ARGS_FAST_DBM_2SRCS	GEN_ARGS_FAST_DBM_2SRCS(KERN_ARGS)
#define KERN_ARGS_FAST_DBM_1S_		GEN_ARGS_FAST_DBM_1S_(KERN_ARGS)
#define KERN_ARGS_FAST_DBM_1S_1SRC	GEN_ARGS_FAST_DBM_1S_1SRC(KERN_ARGS)
#define KERN_ARGS_FAST_DBM_1SRC		GEN_ARGS_FAST_DBM_1SRC(KERN_ARGS)
#define KERN_ARGS_FAST_DBM_SBM		GEN_ARGS_FAST_DBM_SBM(KERN_ARGS)

#define KERN_ARGS_EQSP_DBM_2SRCS	GEN_ARGS_EQSP_DBM_2SRCS(KERN_ARGS)
#define KERN_ARGS_EQSP_DBM_1S_		GEN_ARGS_EQSP_DBM_1S_(KERN_ARGS)
#define KERN_ARGS_EQSP_DBM_1S_1SRC	GEN_ARGS_EQSP_DBM_1S_1SRC(KERN_ARGS)
#define KERN_ARGS_EQSP_DBM_1SRC		GEN_ARGS_EQSP_DBM_1SRC(KERN_ARGS)
#define KERN_ARGS_EQSP_DBM_SBM		GEN_ARGS_EQSP_DBM_SBM(KERN_ARGS)

#define KERN_ARGS_SLOW_DBM_2SRCS	GEN_ARGS_SLOW_DBM_2SRCS(KERN_ARGS)
#define KERN_ARGS_SLOW_DBM_1S_		GEN_ARGS_SLOW_DBM_1S_(KERN_ARGS)
#define KERN_ARGS_SLOW_DBM_1S_1SRC	GEN_ARGS_SLOW_DBM_1S_1SRC(KERN_ARGS)
#define KERN_ARGS_SLOW_DBM_1SRC		GEN_ARGS_SLOW_DBM_1SRC(KERN_ARGS)
#define KERN_ARGS_SLOW_DBM_SBM		GEN_ARGS_SLOW_DBM_SBM(KERN_ARGS)


#define KERN_ARGS_FLEN_DBM_2SRCS	GEN_ARGS_FLEN_DBM_2SRCS(KERN_ARGS)
#define KERN_ARGS_FLEN_DBM_1S_		GEN_ARGS_FLEN_DBM_1S_(KERN_ARGS)
#define KERN_ARGS_FLEN_DBM_1S_1SRC	GEN_ARGS_FLEN_DBM_1S_1SRC(KERN_ARGS)
#define KERN_ARGS_FLEN_DBM_1SRC		GEN_ARGS_FLEN_DBM_1SRC(KERN_ARGS)
#define KERN_ARGS_FLEN_DBM_SBM		GEN_ARGS_FLEN_DBM_SBM(KERN_ARGS)

#define KERN_ARGS_ELEN_DBM_2SRCS	GEN_ARGS_ELEN_DBM_2SRCS(KERN_ARGS)
#define KERN_ARGS_ELEN_DBM_1S_		GEN_ARGS_ELEN_DBM_1S_(KERN_ARGS)
#define KERN_ARGS_ELEN_DBM_1S_1SRC	GEN_ARGS_ELEN_DBM_1S_1SRC(KERN_ARGS)
#define KERN_ARGS_ELEN_DBM_1SRC		GEN_ARGS_ELEN_DBM_1SRC(KERN_ARGS)
#define KERN_ARGS_ELEN_DBM_SBM		GEN_ARGS_ELEN_DBM_SBM(KERN_ARGS)

#define KERN_ARGS_SLEN_DBM_2SRCS	GEN_ARGS_SLEN_DBM_2SRCS(KERN_ARGS)
#define KERN_ARGS_SLEN_DBM_1S_		GEN_ARGS_SLEN_DBM_1S_(KERN_ARGS)
#define KERN_ARGS_SLEN_DBM_1S_1SRC	GEN_ARGS_SLEN_DBM_1S_1SRC(KERN_ARGS)
#define KERN_ARGS_SLEN_DBM_1SRC		GEN_ARGS_SLEN_DBM_1SRC(KERN_ARGS)
#define KERN_ARGS_SLEN_DBM_SBM		GEN_ARGS_SLEN_DBM_SBM(KERN_ARGS)

/////////////////////

// real, source bitmap

#define KERN_ARGS_FAST_SBM_1		GEN_ARGS_FAST_SBM_1(KERN_ARGS)
#define KERN_ARGS_FAST_SBM_3		GEN_ARGS_FAST_SBM_3(KERN_ARGS)
#define KERN_ARGS_FAST_SBM_1S_2	GEN_ARGS_FAST_SBM_1S_2(KERN_ARGS)
#define KERN_ARGS_FAST_SBM_2S_1	GEN_ARGS_FAST_SBM_2S_1(KERN_ARGS)

// complex, source bitmap

#define KERN_ARGS_FAST_SBM_CPX_3	GEN_ARGS_FAST_SBM_CPX_3(KERN_ARGS)
#define KERN_ARGS_FAST_SBM_CPX_1S_2	GEN_ARGS_FAST_SBM_CPX_1S_2(KERN_ARGS)
#define KERN_ARGS_FAST_SBM_CPX_2S_1	GEN_ARGS_FAST_SBM_CPX_2S_1(KERN_ARGS)

// quaternion, source bitmap

#define KERN_ARGS_FAST_SBM_QUAT_3	GEN_ARGS_FAST_SBM_QUAT_3(KERN_ARGS)
#define KERN_ARGS_FAST_SBM_QUAT_1S_2	GEN_ARGS_FAST_SBM_QUAT_1S_2(KERN_ARGS)
#define KERN_ARGS_FAST_SBM_QUAT_2S_1	GEN_ARGS_FAST_SBM_QUAT_2S_1(KERN_ARGS)

/////////////////////

// real, source bitmap

#define KERN_ARGS_EQSP_SBM_1		GEN_ARGS_EQSP_SBM_1(KERN_ARGS)
#define KERN_ARGS_EQSP_SBM_3		GEN_ARGS_EQSP_SBM_3(KERN_ARGS)
#define KERN_ARGS_EQSP_SBM_1S_2		GEN_ARGS_EQSP_SBM_1S_2(KERN_ARGS)
#define KERN_ARGS_EQSP_SBM_2S_1		GEN_ARGS_EQSP_SBM_2S_1(KERN_ARGS)

// complex, source bitmap

#define KERN_ARGS_EQSP_SBM_CPX_3	GEN_ARGS_EQSP_SBM_CPX_3(KERN_ARGS)
#define KERN_ARGS_EQSP_SBM_CPX_1S_2	GEN_ARGS_EQSP_SBM_CPX_1S_2(KERN_ARGS)
#define KERN_ARGS_EQSP_SBM_CPX_2S_1	GEN_ARGS_EQSP_SBM_CPX_2S_1(KERN_ARGS)

// quaternion, source bitmap

#define KERN_ARGS_EQSP_SBM_QUAT_3	GEN_ARGS_EQSP_SBM_QUAT_3(KERN_ARGS)
#define KERN_ARGS_EQSP_SBM_QUAT_1S_2	GEN_ARGS_EQSP_SBM_QUAT_1S_2(KERN_ARGS)
#define KERN_ARGS_EQSP_SBM_QUAT_2S_1	GEN_ARGS_EQSP_SBM_QUAT_2S_1(KERN_ARGS)

/////////////////////

// real, source bitmap

#define KERN_ARGS_SLOW_SBM_1		GEN_ARGS_SLOW_SBM_1(KERN_ARGS)
#define KERN_ARGS_SLOW_SBM_3		GEN_ARGS_SLOW_SBM_3(KERN_ARGS)
#define KERN_ARGS_SLOW_SBM_1S_2		GEN_ARGS_SLOW_SBM_1S_2(KERN_ARGS)
#define KERN_ARGS_SLOW_SBM_2S_1		GEN_ARGS_SLOW_SBM_2S_1(KERN_ARGS)

// complex, source bitmap

#define KERN_ARGS_SLOW_SBM_CPX_3	GEN_ARGS_SLOW_SBM_CPX_3(KERN_ARGS)
#define KERN_ARGS_SLOW_SBM_CPX_1S_2	GEN_ARGS_SLOW_SBM_CPX_1S_2(KERN_ARGS)
#define KERN_ARGS_SLOW_SBM_CPX_2S_1	GEN_ARGS_SLOW_SBM_CPX_2S_1(KERN_ARGS)

// quaternion, source bitmap

#define KERN_ARGS_SLOW_SBM_QUAT_3	GEN_ARGS_SLOW_SBM_QUAT_3(KERN_ARGS)
#define KERN_ARGS_SLOW_SBM_QUAT_1S_2	GEN_ARGS_SLOW_SBM_QUAT_1S_2(KERN_ARGS)
#define KERN_ARGS_SLOW_SBM_QUAT_2S_1	GEN_ARGS_SLOW_SBM_QUAT_2S_1(KERN_ARGS)


/////////////////////

// real, source bitmap

#define KERN_ARGS_FLEN_SBM_1		GEN_ARGS_FLEN_SBM_1(KERN_ARGS)
#define KERN_ARGS_FLEN_SBM_3		GEN_ARGS_FLEN_SBM_3(KERN_ARGS)
#define KERN_ARGS_FLEN_SBM_1S_2		GEN_ARGS_FLEN_SBM_1S_2(KERN_ARGS)
#define KERN_ARGS_FLEN_SBM_2S_1		GEN_ARGS_FLEN_SBM_2S_1(KERN_ARGS)

// complex, source bitmap

#define KERN_ARGS_FLEN_SBM_CPX_3	GEN_ARGS_FLEN_SBM_CPX_3(KERN_ARGS)
#define KERN_ARGS_FLEN_SBM_CPX_1S_2	GEN_ARGS_FLEN_SBM_CPX_1S_2(KERN_ARGS)
#define KERN_ARGS_FLEN_SBM_CPX_2S_1	GEN_ARGS_FLEN_SBM_CPX_2S_1(KERN_ARGS)

// quaternion, source bitmap

#define KERN_ARGS_FLEN_SBM_QUAT_3	GEN_ARGS_FLEN_SBM_QUAT_3(KERN_ARGS)
#define KERN_ARGS_FLEN_SBM_QUAT_1S_2	GEN_ARGS_FLEN_SBM_QUAT_1S_2(KERN_ARGS)
#define KERN_ARGS_FLEN_SBM_QUAT_2S_1	GEN_ARGS_FLEN_SBM_QUAT_2S_1(KERN_ARGS)

/////////////////////

// real, source bitmap

#define KERN_ARGS_ELEN_SBM_1		GEN_ARGS_ELEN_SBM_1(KERN_ARGS)
#define KERN_ARGS_ELEN_SBM_3		GEN_ARGS_ELEN_SBM_3(KERN_ARGS)
#define KERN_ARGS_ELEN_SBM_1S_2		GEN_ARGS_ELEN_SBM_1S_2(KERN_ARGS)
#define KERN_ARGS_ELEN_SBM_2S_1		GEN_ARGS_ELEN_SBM_2S_1(KERN_ARGS)

// complex, source bitmap

#define KERN_ARGS_ELEN_SBM_CPX_3	GEN_ARGS_ELEN_SBM_CPX_3(KERN_ARGS)
#define KERN_ARGS_ELEN_SBM_CPX_1S_2	GEN_ARGS_ELEN_SBM_CPX_1S_2(KERN_ARGS)
#define KERN_ARGS_ELEN_SBM_CPX_2S_1	GEN_ARGS_ELEN_SBM_CPX_2S_1(KERN_ARGS)

// quaternion, source bitmap

#define KERN_ARGS_ELEN_SBM_QUAT_3	GEN_ARGS_ELEN_SBM_QUAT_3(KERN_ARGS)
#define KERN_ARGS_ELEN_SBM_QUAT_1S_2	GEN_ARGS_ELEN_SBM_QUAT_1S_2(KERN_ARGS)
#define KERN_ARGS_ELEN_SBM_QUAT_2S_1	GEN_ARGS_ELEN_SBM_QUAT_2S_1(KERN_ARGS)

/////////////////////

// real, source bitmap

#define KERN_ARGS_SLEN_SBM_1		GEN_ARGS_SLEN_SBM_1(KERN_ARGS)
#define KERN_ARGS_SLEN_SBM_3		GEN_ARGS_SLEN_SBM_3(KERN_ARGS)
#define KERN_ARGS_SLEN_SBM_1S_2		GEN_ARGS_SLEN_SBM_1S_2(KERN_ARGS)
#define KERN_ARGS_SLEN_SBM_2S_1		GEN_ARGS_SLEN_SBM_2S_1(KERN_ARGS)

// complex, source bitmap

#define KERN_ARGS_SLEN_SBM_CPX_3	GEN_ARGS_SLEN_SBM_CPX_3(KERN_ARGS)
#define KERN_ARGS_SLEN_SBM_CPX_1S_2	GEN_ARGS_SLEN_SBM_CPX_1S_2(KERN_ARGS)
#define KERN_ARGS_SLEN_SBM_CPX_2S_1	GEN_ARGS_SLEN_SBM_CPX_2S_1(KERN_ARGS)

// quaternion, source bitmap

#define KERN_ARGS_SLEN_SBM_QUAT_3	GEN_ARGS_SLEN_SBM_QUAT_3(KERN_ARGS)
#define KERN_ARGS_SLEN_SBM_QUAT_1S_2	GEN_ARGS_SLEN_SBM_QUAT_1S_2(KERN_ARGS)
#define KERN_ARGS_SLEN_SBM_QUAT_2S_1	GEN_ARGS_SLEN_SBM_QUAT_2S_1(KERN_ARGS)


///////////////////////////


#endif // _GPU_ARGS_H_
