// These are the variables declared for use in the host functions

#define DECLARE_SLOW_VARS_SBM_3	DECLARE_SLOW_VARS_3 DECLARE_SLOW_VARS_SBM
#define DECLARE_SLOW_VARS_SBM_2	DECLARE_SLOW_VARS_2 DECLARE_SLOW_VARS_SBM
#define DECLARE_SLOW_VARS_SBM_1	DECLARE_SLOW_VARS_1 DECLARE_SLOW_VARS_SBM

#define DECLARE_SLOW_VARS_DBM_		DECLARE_SLOW_VARS_DBM DECLARE_SLOW_LEN

#define DECLARE_SLOW_VARS_DBM_2SRCS	DECLARE_SLOW_VARS_2SRCS DECLARE_SLOW_VARS_DBM
#define DECLARE_SLOW_VARS_DBM_1SRC	DECLARE_SLOW_VARS_1SRC DECLARE_SLOW_VARS_DBM
#define DECLARE_SLOW_VARS_DBM_SBM	DECLARE_SLOW_VARS_DBM	\
					DECLARE_SLOW_VARS_SBM	\
					DECLARE_SLOW_LEN

