

#define XFER_FAST_ARGS_SBM_3		XFER_FAST_ARGS_SBM XFER_FAST_ARGS_3
#define XFER_EQSP_ARGS_SBM_3		XFER_EQSP_ARGS_SBM XFER_EQSP_ARGS_3
#define XFER_SLOW_ARGS_SBM_3		XFER_SLOW_ARGS_SBM XFER_SLOW_ARGS_3

#define XFER_FAST_ARGS_SBM_1		XFER_FAST_ARGS_SBM XFER_FAST_ARGS_1
#define XFER_EQSP_ARGS_SBM_1		XFER_EQSP_ARGS_SBM XFER_EQSP_ARGS_1
#define XFER_SLOW_ARGS_SBM_1		XFER_SLOW_ARGS_SBM XFER_SLOW_ARGS_1

#define XFER_FAST_ARGS_SBM_1S_2		XFER_FAST_ARGS_SBM XFER_FAST_ARGS_1S_2
#define XFER_EQSP_ARGS_SBM_1S_2		XFER_EQSP_ARGS_SBM XFER_EQSP_ARGS_1S_2
#define XFER_SLOW_ARGS_SBM_1S_2		XFER_SLOW_ARGS_SBM XFER_SLOW_ARGS_1S_2

#define XFER_FAST_ARGS_SBM_2S_1		XFER_FAST_ARGS_SBM XFER_FAST_ARGS_2S_1
#define XFER_EQSP_ARGS_SBM_2S_1		XFER_EQSP_ARGS_SBM XFER_EQSP_ARGS_2S_1
#define XFER_SLOW_ARGS_SBM_2S_1		XFER_SLOW_ARGS_SBM XFER_SLOW_ARGS_2S_1

#define XFER_FAST_ARGS_SBM_CPX_3	XFER_FAST_ARGS_SBM XFER_FAST_ARGS_CPX_3
#define XFER_EQSP_ARGS_SBM_CPX_3	XFER_EQSP_ARGS_SBM XFER_EQSP_ARGS_CPX_3
#define XFER_SLOW_ARGS_SBM_CPX_3	XFER_SLOW_ARGS_SBM XFER_SLOW_ARGS_CPX_3

#define XFER_FAST_ARGS_SBM_CPX_1S_2	XFER_FAST_ARGS_SBM XFER_FAST_ARGS_CPX_1S_2
#define XFER_EQSP_ARGS_SBM_CPX_1S_2	XFER_EQSP_ARGS_SBM XFER_EQSP_ARGS_CPX_1S_2
#define XFER_SLOW_ARGS_SBM_CPX_1S_2	XFER_SLOW_ARGS_SBM XFER_SLOW_ARGS_CPX_1S_2

#define XFER_FAST_ARGS_SBM_CPX_2S_1	XFER_FAST_ARGS_SBM XFER_FAST_ARGS_CPX_2S_1
#define XFER_EQSP_ARGS_SBM_CPX_2S_1	XFER_EQSP_ARGS_SBM XFER_EQSP_ARGS_CPX_2S_1
#define XFER_SLOW_ARGS_SBM_CPX_2S_1	XFER_SLOW_ARGS_SBM XFER_SLOW_ARGS_CPX_2S_1

#define XFER_FAST_ARGS_SBM_QUAT_3	XFER_FAST_ARGS_SBM XFER_FAST_ARGS_QUAT_3
#define XFER_EQSP_ARGS_SBM_QUAT_3	XFER_EQSP_ARGS_SBM XFER_EQSP_ARGS_QUAT_3
#define XFER_SLOW_ARGS_SBM_QUAT_3	XFER_SLOW_ARGS_SBM XFER_SLOW_ARGS_QUAT_3

#define XFER_FAST_ARGS_SBM_QUAT_1S_2	XFER_FAST_ARGS_SBM XFER_FAST_ARGS_QUAT_1S_2
#define XFER_EQSP_ARGS_SBM_QUAT_1S_2	XFER_EQSP_ARGS_SBM XFER_EQSP_ARGS_QUAT_1S_2
#define XFER_SLOW_ARGS_SBM_QUAT_1S_2	XFER_SLOW_ARGS_SBM XFER_SLOW_ARGS_QUAT_1S_2

#define XFER_FAST_ARGS_SBM_QUAT_2S_1	XFER_FAST_ARGS_SBM XFER_FAST_ARGS_QUAT_2S_1
#define XFER_EQSP_ARGS_SBM_QUAT_2S_1	XFER_EQSP_ARGS_SBM XFER_EQSP_ARGS_QUAT_2S_1
#define XFER_SLOW_ARGS_SBM_QUAT_2S_1	XFER_SLOW_ARGS_SBM XFER_SLOW_ARGS_QUAT_2S_1

#define XFER_FAST_ARGS_DBM_2SRCS	XFER_FAST_ARGS_DBM_1SRC XFER_FAST_ARGS_SRC2
#define XFER_EQSP_ARGS_DBM_2SRCS	XFER_EQSP_ARGS_DBM_1SRC XFER_FAST_ARGS_SRC2
#define XFER_SLOW_ARGS_DBM_2SRCS	XFER_SLOW_ARGS_DBM XFER_SLOW_ARGS_2SRCS

#define XFER_FAST_ARGS_DBM_1S_		XFER_FAST_ARGS_DBM XFER_ARGS_1S
#define XFER_EQSP_ARGS_DBM_1S_		XFER_EQSP_ARGS_DBM XFER_ARGS_1S
#define XFER_SLOW_ARGS_DBM_1S_		XFER_SLOW_ARGS_DBM XFER_ARGS_1S

#define XFER_FAST_ARGS_DBM_1S_1SRC	XFER_FAST_ARGS_DBM_1SRC XFER_ARGS_1S
#define XFER_EQSP_ARGS_DBM_1S_1SRC	XFER_EQSP_ARGS_DBM_1SRC XFER_ARGS_1S
#define XFER_SLOW_ARGS_DBM_1S_1SRC	XFER_SLOW_ARGS_DBM_1SRC XFER_ARGS_1S

#define XFER_FAST_ARGS_DBM_1SRC	XFER_FAST_ARGS_DBM XFER_FAST_ARGS_SRC1 XFER_FAST_COUNT(src1_dp)
#define XFER_EQSP_ARGS_DBM_1SRC	XFER_EQSP_ARGS_DBM XFER_FAST_ARGS_SRC1 XFER_EQSP_COUNT(src1_dp)
#define XFER_SLOW_ARGS_DBM_1SRC	XFER_SLOW_ARGS_DBM XFER_SLOW_ARGS_SRC1

#define XFER_FAST_ARGS_DBM_1S	XFER_FAST_ARGS_DBM XFER_ARGS_1S XFER_FAST_COUNT(bitmap_dst_dp)
#define XFER_EQSP_ARGS_DBM_1S	XFER_EQSP_ARGS_DBM XFER_ARGS_1S XFER_EQSP_COUNT(bitmap_dst_dp)
#define XFER_SLOW_ARGS_DBM_1S	XFER_SLOW_ARGS_DBM XFER_ARGS_1S

#define XFER_FAST_ARGS_3S_1	XFER_FAST_ARGS_1 XFER_ARGS_3S
#define XFER_EQSP_ARGS_3S_1	XFER_EQSP_ARGS_1 XFER_ARGS_3S
#define XFER_SLOW_ARGS_3S_1	XFER_SLOW_ARGS_1 XFER_ARGS_3S

#define XFER_FAST_ARGS_3S_2	XFER_FAST_ARGS_2 XFER_ARGS_3S
#define XFER_EQSP_ARGS_3S_2	XFER_EQSP_ARGS_2 XFER_ARGS_3S
#define XFER_SLOW_ARGS_3S_2	XFER_SLOW_ARGS_2 XFER_ARGS_3S

#define XFER_FAST_ARGS_2S_3	XFER_FAST_ARGS_3 XFER_ARGS_2S
#define XFER_EQSP_ARGS_2S_3	XFER_EQSP_ARGS_3 XFER_ARGS_2S
#define XFER_SLOW_ARGS_2S_3	XFER_SLOW_ARGS_3 XFER_ARGS_2S

#define XFER_FAST_ARGS_1S_4	XFER_FAST_ARGS_4 XFER_ARGS_1S
#define XFER_EQSP_ARGS_1S_4	XFER_EQSP_ARGS_4 XFER_ARGS_1S
#define XFER_SLOW_ARGS_1S_4	XFER_SLOW_ARGS_4 XFER_ARGS_1S

#define XFER_FAST_ARGS_1S_1	XFER_FAST_ARGS_1 XFER_ARGS_1S
#define XFER_EQSP_ARGS_1S_1	XFER_EQSP_ARGS_1 XFER_ARGS_1S
#define XFER_SLOW_ARGS_1S_1	XFER_SLOW_ARGS_1 XFER_ARGS_1S

#define XFER_FAST_ARGS_1S_2	XFER_FAST_ARGS_2 XFER_ARGS_1S
#define XFER_EQSP_ARGS_1S_2	XFER_EQSP_ARGS_2 XFER_ARGS_1S
#define XFER_SLOW_ARGS_1S_2	XFER_SLOW_ARGS_2 XFER_ARGS_1S

#define XFER_FAST_ARGS_2S_1	XFER_FAST_ARGS_1 XFER_ARGS_2S
#define XFER_EQSP_ARGS_2S_1	XFER_EQSP_ARGS_1 XFER_ARGS_2S
#define XFER_SLOW_ARGS_2S_1	XFER_SLOW_ARGS_1 XFER_ARGS_2S

#define XFER_SLOW_ARGS_3S_1	XFER_SLOW_ARGS_1 XFER_ARGS_3S

#define XFER_FAST_ARGS_2SRCS	XFER_FAST_ARGS_SRC1 XFER_FAST_ARGS_SRC2
#define XFER_EQSP_ARGS_2SRCS	XFER_EQSP_ARGS_SRC1 XFER_EQSP_ARGS_SRC2
#define XFER_SLOW_ARGS_2SRCS	XFER_SLOW_ARGS_SRC1 XFER_SLOW_ARGS_SRC2

#define XFER_FAST_ARGS_CPX_1	XFER_FAST_ARGS_1
#define XFER_EQSP_ARGS_CPX_1	XFER_EQSP_ARGS_1
#define XFER_SLOW_ARGS_CPX_1	XFER_SLOW_ARGS_1

#define XFER_FAST_ARGS_CPX_2	XFER_FAST_ARGS_2
#define XFER_EQSP_ARGS_CPX_2	XFER_EQSP_ARGS_2
#define XFER_SLOW_ARGS_CPX_2	XFER_SLOW_ARGS_2

#define XFER_FAST_ARGS_CPX_3	XFER_FAST_ARGS_3
#define XFER_EQSP_ARGS_CPX_3	XFER_EQSP_ARGS_3
#define XFER_SLOW_ARGS_CPX_3	XFER_SLOW_ARGS_3

#define XFER_FAST_ARGS_CPX_2S_1	XFER_FAST_ARGS_1 XFER_ARGS_CPX_2S
#define XFER_EQSP_ARGS_CPX_2S_1	XFER_EQSP_ARGS_1 XFER_ARGS_CPX_2S
#define XFER_SLOW_ARGS_CPX_2S_1	XFER_SLOW_ARGS_1 XFER_ARGS_CPX_2S

#define XFER_FAST_ARGS_QUAT_1	XFER_FAST_ARGS_1
#define XFER_EQSP_ARGS_QUAT_1	XFER_EQSP_ARGS_1
#define XFER_SLOW_ARGS_QUAT_1	XFER_SLOW_ARGS_1

#define XFER_FAST_ARGS_QUAT_2	XFER_FAST_ARGS_2
#define XFER_EQSP_ARGS_QUAT_2	XFER_EQSP_ARGS_2
#define XFER_SLOW_ARGS_QUAT_2	XFER_SLOW_ARGS_2

#define XFER_FAST_ARGS_QUAT_3	XFER_FAST_ARGS_3
#define XFER_EQSP_ARGS_QUAT_3	XFER_EQSP_ARGS_3
#define XFER_SLOW_ARGS_QUAT_3	XFER_SLOW_ARGS_3

#define XFER_FAST_ARGS_QUAT_2S_1	XFER_FAST_ARGS_1 XFER_ARGS_QUAT_2S
#define XFER_EQSP_ARGS_QUAT_2S_1	XFER_EQSP_ARGS_1 XFER_ARGS_QUAT_2S
#define XFER_SLOW_ARGS_QUAT_2S_1	XFER_SLOW_ARGS_1 XFER_ARGS_QUAT_2S

#define XFER_FAST_ARGS_RC_2	XFER_FAST_ARGS_2
#define XFER_EQSP_ARGS_RC_2	XFER_EQSP_ARGS_2
#define XFER_SLOW_ARGS_RC_2	XFER_SLOW_ARGS_2

#define XFER_FAST_ARGS_CR_2	XFER_FAST_ARGS_2
#define XFER_EQSP_ARGS_CR_2	XFER_EQSP_ARGS_2
#define XFER_SLOW_ARGS_CR_2	XFER_SLOW_ARGS_2

#define XFER_FAST_ARGS_CCR_3	XFER_FAST_ARGS_3
#define XFER_EQSP_ARGS_CCR_3	XFER_EQSP_ARGS_3
#define XFER_SLOW_ARGS_CCR_3	XFER_SLOW_ARGS_3

#define XFER_FAST_ARGS_CR_1S_2	XFER_FAST_ARGS_1S_2
#define XFER_EQSP_ARGS_CR_1S_2	XFER_EQSP_ARGS_1S_2
#define XFER_SLOW_ARGS_CR_1S_2	XFER_SLOW_ARGS_1S_2

#define XFER_FAST_ARGS_CPX_1S_2	XFER_FAST_ARGS_2 XFER_ARGS_CPX_1S
#define XFER_EQSP_ARGS_CPX_1S_2	XFER_EQSP_ARGS_2 XFER_ARGS_CPX_1S
#define XFER_SLOW_ARGS_CPX_1S_2	XFER_SLOW_ARGS_2 XFER_ARGS_CPX_1S

#define XFER_FAST_ARGS_CPX_1S_1	XFER_FAST_ARGS_1 XFER_ARGS_CPX_1S
#define XFER_EQSP_ARGS_CPX_1S_1	XFER_EQSP_ARGS_1 XFER_ARGS_CPX_1S
#define XFER_SLOW_ARGS_CPX_1S_1	XFER_SLOW_ARGS_1 XFER_ARGS_CPX_1S

#define XFER_FAST_ARGS_RQ_2	XFER_FAST_ARGS_2
#define XFER_EQSP_ARGS_RQ_2	XFER_EQSP_ARGS_2
#define XFER_SLOW_ARGS_RQ_2	XFER_SLOW_ARGS_2

#define XFER_FAST_ARGS_QR_2	XFER_FAST_ARGS_2
#define XFER_EQSP_ARGS_QR_2	XFER_EQSP_ARGS_2
#define XFER_SLOW_ARGS_QR_2	XFER_SLOW_ARGS_2

#define XFER_FAST_ARGS_QQR_3	XFER_FAST_ARGS_3
#define XFER_EQSP_ARGS_QQR_3	XFER_EQSP_ARGS_3
#define XFER_SLOW_ARGS_QQR_3	XFER_SLOW_ARGS_3

#define XFER_FAST_ARGS_QR_1S_2	XFER_FAST_ARGS_1S_2
#define XFER_EQSP_ARGS_QR_1S_2	XFER_EQSP_ARGS_1S_2
#define XFER_SLOW_ARGS_QR_1S_2	XFER_SLOW_ARGS_1S_2

#define XFER_FAST_ARGS_QUAT_1S_2	XFER_FAST_ARGS_2 XFER_ARGS_QUAT_1S
#define XFER_EQSP_ARGS_QUAT_1S_2	XFER_EQSP_ARGS_2 XFER_ARGS_QUAT_1S
#define XFER_SLOW_ARGS_QUAT_1S_2	XFER_SLOW_ARGS_2 XFER_ARGS_QUAT_1S

#define XFER_FAST_ARGS_QUAT_1S_1	XFER_FAST_ARGS_1 XFER_ARGS_QUAT_1S
#define XFER_EQSP_ARGS_QUAT_1S_1	XFER_EQSP_ARGS_1 XFER_ARGS_QUAT_1S
#define XFER_SLOW_ARGS_QUAT_1S_1	XFER_SLOW_ARGS_1 XFER_ARGS_QUAT_1S

#define XFER_FAST_ARGS_2	XFER_FAST_ARGS_1 XFER_FAST_ARGS_SRC1

#define XFER_FAST_ARGS_DBM					\
	va1.va_dest	= bitmap_dst_dp->dt_data;		\
	va1.va_bit0	= bitmap_dst_dp->dt_bit0;

#define XFER_FAST_ARGS_SBM					\
	va1.va_sbm_p	= bitmap_src_dp->dt_data;		\
	va1.va_bit0	= bitmap_src_dp->dt_bit0;

#define XFER_EQSP_ARGS_DBM					\
	va1.va_dest	= bitmap_dst_dp->dt_data;		\
	va1.va_bit0	= bitmap_dst_dp->dt_bit0;		\
	XFER_INCR(spi_dst_incr, bitmap_dst_dp)

#define XFER_EQSP_ARGS_SBM					\
	va1.va_sbm_p	= bitmap_src_dp->dt_data;		\
	va1.va_bit0	= bitmap_src_dp->dt_bit0;

#define XFER_ARGS_1S						\
	va1.scalar_val1	= (oap->oa_svp[0])->std_scalar;

#define XFER_ARGS_CPX_1S					\
	va1.cpx_scalar_val1	= (oap->oa_svp[0])->std_cpx_scalar;

#define XFER_ARGS_CPX_2S					\
	XFER_ARGS_CPX_1S					\
	va1.cpx_scalar_val2	= (oap->oa_svp[1])->std_cpx_scalar;

#define XFER_ARGS_QUAT_1S					\
	va1.quat_scalar_val1	= (oap->oa_svp[0])->std_quat_scalar;

#define XFER_ARGS_QUAT_2S					\
	XFER_ARGS_QUAT_1S					\
	va1.quat_scalar_val2	= (oap->oa_svp[1])->std_quat_scalar;

#define XFER_ARGS_3S						\
	XFER_ARGS_2S						\
	va1.scalar_val3	= (oap->oa_svp[2])->std_scalar;

#define XFER_ARGS_2S						\
	XFER_ARGS_1S						\
	va1.scalar_val2	= (oap->oa_svp[1])->std_scalar;

/*
#define XFER_FAST_ARGS_DBM					\
	va1.va_dest	= bitmap_dst_dp->dt_data;		\
	va1.va_bit0	= bitmap_dst_dp->dt_bit0;
#define XFER_SLOW_ARGS_1					\
	SLOW_ARGS_SETUP						\
	va1.va_dest	= dst_dp->dt_data;			\
	va1.va_dinc	= dst_dp->dt_type_inc;			\
	va1.va_count	= dst_dp->dt_type_dim;

	*/

#define XFER_SLOW_ARGS_DBM	SLOW_ARGS_SETUP					\
				va1.va_dest	= bitmap_dst_dp->dt_data;	\
				va1.va_dinc	= bitmap_dst_dp->dt_type_inc;	\
				va1.va_count	= bitmap_dst_dp->dt_type_dim;	\
				va1.va_bit0	= bitmap_dst_dp->dt_bit0;

#define XFER_SLOW_ARGS_SBM	SLOW_ARGS_SETUP					\
				va1.va_sbm_p	= bitmap_src_dp->dt_data;	\
				va1.va_sbm_inc	= bitmap_src_dp->dt_type_inc;	\
				va1.va_sbm_count= bitmap_src_dp->dt_type_dim;	\
				va1.va_bit0	= bitmap_src_dp->dt_bit0;



#define XFER_FAST_ARGS_2	XFER_FAST_ARGS_1 XFER_FAST_ARGS_SRC1
#define XFER_SLOW_ARGS_2	XFER_SLOW_ARGS_1 XFER_SLOW_ARGS_SRC1
#define XFER_FAST_ARGS_3	XFER_FAST_ARGS_2 XFER_FAST_ARGS_SRC2
#define XFER_SLOW_ARGS_3	XFER_SLOW_ARGS_2 XFER_SLOW_ARGS_SRC2
#define XFER_FAST_ARGS_4	XFER_FAST_ARGS_3 XFER_FAST_ARGS_SRC3
#define XFER_SLOW_ARGS_4	XFER_SLOW_ARGS_3 XFER_SLOW_ARGS_SRC3
#define XFER_FAST_ARGS_5	XFER_FAST_ARGS_4 XFER_FAST_ARGS_SRC4
#define XFER_SLOW_ARGS_5	XFER_SLOW_ARGS_4 XFER_SLOW_ARGS_SRC4

#define SHOW_ARG_DP(stem)	sprintf(error_string,"%s object:  %s",#stem,stem##_dp->dt_name);\
				advise(error_string);

#define XFER_FAST_ARGS_1	va1.va_dest	= dst_dp->dt_data;	\
				XFER_FAST_COUNT(dst_dp)

#define XFER_FAST_COUNT(dp)	va1.va_len	= dp->dt_n_type_elts;

#define XFER_EQSP_COUNT(dp)	va1.va_len	= dp->dt_n_type_elts;

#define XFER_FAST_ARGS_SRC1	va1.va_src1 = src1_dp->dt_data;
#define XFER_FAST_ARGS_SRC2	va1.va_src2 = src2_dp->dt_data;
#define XFER_FAST_ARGS_SRC3	va1.va_src3 = src3_dp->dt_data;
#define XFER_FAST_ARGS_SRC4	va1.va_src4 = src4_dp->dt_data;

#define XFER_ARGS_EXTLOC	va1.va_sval[0].u_ul=dst_dp->dt_n_type_elts;	\
				/* Need to do something here for the return scalars... */

#define XFER_FAST_ARGS_EXTLOC	XFER_FAST_ARGS_SRC1		\
				XFER_FAST_COUNT(src1_dp)	\
				va1.va_dest = dst_dp->dt_data;	\
				XFER_ARGS_EXTLOC

#define XFER_SLOW_ARGS_EXTLOC	XFER_SLOW_ARGS_2		\
				XFER_ARGS_EXTLOC

#define SLOW_ARGS_SETUP						\
	va1.va_spi_p = &spi1;					\
	va1.va_szi_p = &szi1;

#define XFER_SLOW_ARGS_1					\
	SLOW_ARGS_SETUP						\
	va1.va_dest	= dst_dp->dt_data;			\
	va1.va_dinc	= dst_dp->dt_type_inc;			\
	va1.va_count	= dst_dp->dt_type_dim;

#define XFER_SLOW_ARGS_SRC1	XFER_SLOW_ARGS_SRC_N(1)
#define XFER_SLOW_ARGS_SRC2	XFER_SLOW_ARGS_SRC_N(2)
#define XFER_SLOW_ARGS_SRC3	XFER_SLOW_ARGS_SRC_N(3)
#define XFER_SLOW_ARGS_SRC4	XFER_SLOW_ARGS_SRC_N(4)

#define XFER_SLOW_ARGS_SRC_N(n)					\
	va1.va_src##n		= src##n##_dp->dt_data;		\
	va1.va_src##n##_inc	= src##n##_dp->dt_type_inc;	\
	va1.va_src##n##_cnt	= src##n##_dp->dt_type_dim;

#define XFER_EQSP_ARGS_2	XFER_EQSP_ARGS_1 XFER_EQSP_ARGS_SRC1
#define XFER_EQSP_ARGS_3	XFER_EQSP_ARGS_2 XFER_EQSP_ARGS_SRC2
#define XFER_EQSP_ARGS_4	XFER_EQSP_ARGS_3 XFER_EQSP_ARGS_SRC3
#define XFER_EQSP_ARGS_5	XFER_EQSP_ARGS_4 XFER_EQSP_ARGS_SRC4

#define XFER_INCR(member,dp)	va1.va_spi_p->member = dp->dt_type_inc;

#define XFER_EQSP_ARGS_1	XFER_FAST_ARGS_1		\
				XFER_INCR(spi_dst_incr, oap->oa_dest)

#define XFER_EQSP_ARGS_SRC1	XFER_FAST_ARGS_SRC1		\
				XFER_INCR(spi_src_incr[0], oap->oa_dp[0])

#define XFER_EQSP_ARGS_SRC2	XFER_FAST_ARGS_SRC2		\
				XFER_INCR(spi_src_incr[1], oap->oa_dp[1])

#define XFER_EQSP_ARGS_SRC3	XFER_FAST_ARGS_SRC3		\
				XFER_INCR(spi_src_incr[2], oap->oa_dp[2])

#define XFER_EQSP_ARGS_SRC4	XFER_FAST_ARGS_SRC4		\
				XFER_INCR(spi_src_incr[3], oap->oa_dp[3])

