
#define	yymaxdepth seq_maxdepth
#define	yyparse	seq_parse
#define	yylex	seq_lex
#define	yyerror	seq_error
#define	yylval	seq_lval
#define	yychar	seq_char
#define	yydebug	seq_debug
#define	yypact	seq_pact	
#define	yyr1	seq_r1			
#define	yyr2	seq_r2			
#define	yydef	seq_def		
#define	yychk	seq_chk		
#define	yypgo	seq_pgo		
#define	yyact	seq_act		
#define	yyexca	seq_exca
#define yyerrflag seq_errflag
#define yynerrs	seq_nerrs
#define	yyps	seq_ps
#define	yypv	seq_pv
#define	yys	seq_s
#define	yy_yys	seq_yys
#define	yystate	seq_state
#define	yytmp	seq_tmp
#define	yyv	seq_v
#define	yy_yyv	seq_yyv
#define	yyval	seq_val
#define	yylloc	seq_lloc
#define yyreds	seq_reds
#define yytoks	seq_toks
#define yylhs	seq_yylhs
#define yylen	seq_yylen
#define yydefred seq_yydefred
#define yydgoto	seq_yydgoto
#define yysindex seq_yysindex
#define yyrindex seq_yyrindex
#define yygindex seq_yygindex
#define yytable	 seq_yytable
#define yycheck	 seq_yycheck
#define yyname   seq_yyname
#define yyrule   seq_yyrule

